### PR TITLE
reverse public repo PR 2790 and move to private repo to fix sync PR

### PR DESCRIPTION
**Pull request by ktoliver**
https://github.com/MicrosoftDocs/architecture-center/pull/2790 was merged with blocking issues in the public repo. Metadata issues are preventing the repo sync PR from being merged, https://github.com/MicrosoftDocs/architecture-center-pr/pull/2985. We're backing out the PR in the public repo and have moved the original commits to the private repo. We'll fix blocking items in the new PR and it will merge there. This PR deletes the files that were in the original pull request from master in this repository.

### CODE REVIEW

**Review by EdPrice-MSFT — APPROVED** [review]
This looks great. Thanks!

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger18** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @pdevito3, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
Thanks @EdPrice-MSFT

**Pull request merged**
