### PR TITLE
Updated graphics for the solution idea "DevOps in a hybrid environment"

### PR DESCRIPTION
**Pull request by t2kx**
graphics were not showing correctly in Docs Darkmode theme , so updated graphics with light background so it can reflect correctly every (in any mode)

### CODE REVIEW

**Comment by PRMerger9** [comment]
@t2kx : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @t2kx - Because your PR updates a config file for the repo, would you submit these updates in the private repo? Let me know if you need information about working in the private repo; I can send it to you via email. Thanks. We'll close this PR.

**Comment by t2kx** [comment]
Darnit, didn't notice the config, you can ignore that!! New pr or just delete the file, your call

**Comment by ktoliver** [comment]
> Darnit, didn't notice the config, you can ignore that!! New pr or just delete the file, your call

@t2kx I don't have the option to delete the file from the PR (it's "grayed out"). (It might be because you are working in master in your fork--or you have a working branch named master; GitHub prefers a non-master working branch.) So, you can delete it or create a new PR--your call. :) Thanks!

**Comment by PRMerger9** [comment]
@t2kx : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by t2kx** [comment]
i'll create a new one without the json

**Pull request closed without merging**
