### PR TITLE
Event Hubs is also a pub/sub system and should be added to the publish/subscribe pattern doc

### PR DESCRIPTION
**Pull request by richardpark-msft**
Just noticed this while reading through the patterns docs for pub/sub - we mention Service Bus and Event Grid but I think EventHubs is also a pub/sub system. 

CC: @kevinlam1 since I believe Event Hubs is yours and I don't want to misstate EH's purpose :)

### CODE REVIEW

**Comment by PRMerger15** [comment]
@richardpark-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by doodlemania2** [comment]
#sign-off

**Comment by PRMerger14** [comment]
@doodlemania2: I'm sorry - only the author of this article, @alexbuckgit, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by kevinlam1** [comment]
@Clemens Vasters<mailto:clemensv@microsoft.com> should also review.

-Kevin

**Pull request merged**
