### PR TITLE
Add content for MMLSpark

### PR DESCRIPTION
**Pull request by esclee**
Added content around MMLSpark on the Data Science and Machine Learning page.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@esclee : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mhamilton723** [comment]
Hey @jborsecnik , Please let us know if there is anything we can do to help this along. Thanks in advance :)

**Comment by Jak-MS** [comment]
@esclee @mhamilton723 - this PR has been assigned to the listed author @MikeWasson. Mike needs to review the changes and approve them before this PR can move forward. Thanks.

in addition, @esclee: as a Microsoft employee and a Program Manger, you should be submitting content through the private repos so that we can take advantage of the staging, proofing, and validation tools there. Here's some information about that:

> Microsoft authors and contributors need to make content contributions through the private repository so the content can be staged and validated by the current validation rules.  
>
> After you review staging and fix all validation issues, you can tag an author for review or add the sign-off comment to let PR reviewers know that the updates are ready to be merged.  
> 
> Read about [authors working in the public repo](https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=master) for more information.  
>
> If you need help getting set up to work in the private repo, see [Set up Git repository locally for documentation](https://review.docs.microsoft.com/en-us/help/contribute/contribute-get-started-setup-local?branch=master).

**Comment by esclee** [comment]
Thank you -- abandoning this PR and starting one from private repo

**Pull request closed without merging**
