### PR TITLE
Fix build issues in metadata

### PR DESCRIPTION
**Pull request by ckittel**
* `author` is not an array  - move back to a string value
* remove `azure-purview` as it is not yet an allowed value by the build pipeline

### CODE REVIEW

**Comment by PRMerger14** [comment]
@ckittel : Thanks for your contribution! The author(s) have been notified to review your proposed change. @pdevito3

**Comment by PRMerger14** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by ktoliver — APPROVED** [review]
Merge build fixes in public repo

In re: https://github.com/MicrosoftDocs/architecture-center/pull/2611, https://github.com/MicrosoftDocs/architecture-center-pr/pull/2354

We'll follow up with a PR in the private repo to fix blocking issues in the original PR 2611

**Comment by ktoliver** [comment]
@ckittel Thanks for this pull request

**Pull request merged**
