### PR TITLE
Correct return code from progress endpoint

### PR DESCRIPTION
**Pull request by SteveDunn**
Progress endpoints should return `200` and not `202` as described here: https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#1327-the-typical-flow-polling

### CODE REVIEW

**Comment by PRMerger5** [comment]
@SteveDunn : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by EdPrice-MSFT — APPROVED** [review]
Great clarifications. Thanks!

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger14** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @WillEastbury, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
