### PR TITLE
Update migrate.md

### PR DESCRIPTION
**Pull request by JanetCThomas**
testing the review process - this is only a test

### CODE REVIEW

**Comment by PRMerger8** [comment]
@JanetCThomas : Thanks for your contribution! The author, @BrianBlanchard, has been notified to review your proposed change.

**Comment by JanetCThomas** [comment]
testing the review process. This is just a test

**Comment by Jak-MS** [comment]
Hi @JanetCThomas - your test worked. :)

Just as an FYI - As a Microsoft Content PM you should be submitting content changes to the private repo: architecture-center-pr instead of the public repo.

Type `#please-close` in a comment when you're done with this PR. 

Thanks.

***
For reference:

Microsoft authors and contributors need to make content contributions through the private repository so the content can be staged and validated by the current validation rules.  

After you review staging and fix all validation issues, you can add the sign-off comment to let PR reviewers know that the updates are ready to be merged.  

Read about [authors working in the public repo](https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=master) for more information.  

If you need help getting set up to work in the private repo, see [Set up Git repository locally for documentation](https://review.docs.microsoft.com/en-us/help/contribute/contribute-get-started-setup-local?branch=master).

**Comment by JanetCThomas** [comment]
#please-close

**Pull request closed without merging**
