### PR TITLE
Added info on Site Recovery for VM failovers

### PR DESCRIPTION
**Pull request by sideeksh**
Site Recovery service info was missing in this document so added one sentence to highlight it.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@sideeksh : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MikeWasson** [comment]
@sideeksh Hi - This doc is specifically technology agnostic. That's why we link to design patterns but not specific technologies or services in the doc. We do link from this doc to our [reliability guidance](https://docs.microsoft.com/en-us/azure/architecture/reliability/index) which includes information about ASR

**Comment by Jak-MS** [comment]
@MikeWasson - can you provide specific guidance for this PR. 

- `#sign-off` if it's ready to merge
- `#hold-off` if it requires changes before it's ready for sign off
- `#please-close` - if these changes aren't going to be merged

Thanks!

**Comment by MikeWasson** [comment]
#please-close

**Pull request closed without merging**
