### PR TITLE
Update CQRS for SEO

### PR DESCRIPTION
**Pull request by adamboeglin**
Update the CQRS article for better SEO

### CODE REVIEW

**Comment by PRMerger15** [comment]
@adamboeglin : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@adamboeglin : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@adamboeglin : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by adamboeglin** [comment]
#sign-off

**Comment by PRMerger9** [comment]
@adamboeglin: I'm sorry - only the author of this article, @dragon119, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request closed without merging**
