### PR TITLE
Update grammar in REST vs RPC section

### PR DESCRIPTION
**Pull request by SamirMohamedCS**
The first sentence of the REST section is grammatically incorrect and awkward sounding. There are a few ways to fix it but I think this edit makes the most sense as it presents the information in a similar manner as the next paragraph on RPC.

### CODE REVIEW

**Comment by MikeWasson** [comment]
"models" is a verb in this sentence. That may be what's confusing, since it could also be a noun. I'll try to clarify.

**Comment by PRMerger6** [comment]
@SamirMohamedCS : Thanks for your contribution! The author, @MikeWasson, has been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@ktoliver : Thanks for your contribution! The author, @MikeWasson, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
@SamirMohamedCS The article updated in this pull request has been revised, and the content no longer exists. Thank you for your contribution. We'll close the pull request now.

**Pull request closed without merging**
