### PR TITLE
Update cloud-scale-analytics-with-discovery-hub.yml

### PR DESCRIPTION
**Pull request by micahdhorner**
We no longer call it "Discovery Hub". Just TimeXtender.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@micahdhorner : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger3** [comment]
@EdPrice-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by micahdhorner** [comment]
Thank you, @EdPrice-MSFT . I am not familiar with GitHub, so I apologize if I did something incorrectly. I've also uploaded an updated reference architecture graphic here: https://i.imgur.com/z4QoIt9.jpg

I appreciate your help getting this updated.

**Comment by micahdhorner** [comment]
@EdPrice-MSFT thanks for your help. I'm new to GitHub, so I apologize if I did something incorrectly.

Here is an updated graphic for the reference architecture: https://imgur.com/7ejIzoo

**Pull request merged**
