### PR TITLE
Update compute-decision-tree.md

### PR DESCRIPTION
**Pull request by microsoftsonny**

### CODE REVIEW

**Comment by PRMerger19** [comment]
@microsoftsonny : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by microsoftsonny** [comment]
@EdPrice-MSFT

**Review by EdPrice-MSFT — APPROVED** [review]
Great catch!

**Comment by PRMerger8** [comment]
@EdPrice-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Pull request merged**
