### PR TITLE
Adding Neptune and Memory DB - #3538

### PR DESCRIPTION
**Pull request by sadukie**
@EdPrice-MSFT These are my proposed changes for #3538.

### CODE REVIEW

**Comment by Jak-MS** [comment]
@svchandramohan 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by EdPrice-MSFT — APPROVED** [review]
Looks great!

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Review by EdPrice-MSFT — APPROVED** [review]
Looks great!

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Pull request merged**
