### PR TITLE
Update design-requirements.md

### PR DESCRIPTION
**Pull request by mustafakaya**
There're duplicated Mean Time Between Failures (MTBF) . I removed one of them and add Mean time to recover (MTTR) metric for determine SLA.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@mustafakaya : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by EdPrice-MSFT — APPROVED** [review]
Great update

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger10** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @v-aangie, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
