### PR TITLE
Create greetings.yml

### PR DESCRIPTION
**Pull request by absheik**
Creating a Greetings action for first time contributors

### CODE REVIEW

**Comment by ktoliver** [comment]
@MikeWasson Could you review this requested addition to the repo? Thanks.

**Comment by david-stanford** [comment]
@absheik do you need to update the text? It looks like it will just display: Message that will be displayed on users'' first issue

**Comment by david-stanford** [comment]
Instead of an actual greeting

**Comment by absheik** [comment]
@david-stanford updated the greetings to be more descriptive

**Comment by david-stanford** [comment]
#sign-off

**Comment by PRMerger15** [comment]
@david-stanford: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
@david-stanford @absheik - Because this is a repo-level change and @MikeWasson is the listed business approver for the repo, we'll ask him to approve the pull request.

@absheik - In the future, would you work in the private repository? Many thanks.

**Comment by absheik** [comment]
#sign off

**Comment by absheik** [comment]
based on feedback decided to not experiment with actions on a Docs repo

**Pull request closed without merging**
