### PR TITLE
Add link to information on latency issues

### PR DESCRIPTION
**Pull request by kbaley**

### CODE REVIEW

**Comment by PRMerger18** [comment]
@kbaley : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ShannonLeavitt** [comment]
@EdPrice-MSFT - Can you review the proposed changes? IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
#assign:@MicrosoftDocs/public-repo-pr-review-team

**Comment by PRMerger17** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: microsoftdocs/public-repo-pr-review-team

**Comment by EdPrice-MSFT** [comment]
It's a good overview, but it's there to advertise the company's services. It's not really about microservices on Azure.

**Comment by kbaley** [comment]
@EdPrice-MSFT It's a link to a blog post on a very well-known topic in distributed computing that I believe is directly relevant to the text in that it's backing up the claim that latency can become a problem. I also don't believe it's promotional as the discussion focuses solely on the concepts with most of the links going to further discussions on the fallacies of distributed computing. It's [not without precedent](https://github.com/MicrosoftDocs/architecture-center/pull/2639) on Microsoft's docs.

**Comment by kbaley** [comment]
Hi everyone. Would it be possible to re-consider based on my previous comments?

**Comment by kbaley** [comment]
@ShannonLeavitt I understand this is closed but was wondering if it could be reconsidered

**Comment by ShannonLeavitt** [comment]
Hi @kbaley - That's a question for @EdPrice-MSFT :)

**Pull request closed without merging**
