### PR TITLE
Update automate-sentinel-integration-content.md

### PR DESCRIPTION
**Pull request by cmaneiro**
Removing customer references

### CODE REVIEW

**Comment by cmaneiro** [comment]
Hi @EdPrice-MSFT 

We found a customer reference in the article, now is removed. 

Thanks

**Review by ckittel — APPROVED** [review]
thanks!

**Comment by ckittel** [comment]
I know this won't work, but note to the PR reviewers, we need this one in.  (Ideally this would have been opened in `-pr` -- but here we are.)

#sign-off

**Comment by PRMerger14** [comment]
@ckittel: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
