### PR TITLE
adding resource and fix table

### PR DESCRIPTION
**Pull request by PixelRobots**
added link to node image auto-upgrade channel. Also fixed table to now say that security patching happens with a node image upgrade.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@PixelRobots : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by EdPrice-MSFT — APPROVED** [review]
Good addition.

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger9** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @rishabhsaha, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
