### PR TITLE
Resolve syncing conflicts from repo_sync_working_branch to master

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by Docs to resolve syncing conflicts from repo_sync_working_branch to master.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@MikeWasson : Thanks for your contribution! The author, @lbrader, has been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@MikeWasson : Thanks for your contribution! The author, @dragon119, has been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@MikeWasson : Thanks for your contribution! The author, @dragon119, has been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@MikeWasson : Thanks for your contribution! The author, @petertay, has been notified to review your proposed change.

**Pull request merged**
