### PR TITLE
Adding LinkedIn link.

### PR DESCRIPTION
**Pull request by mrwalters1988**

### CODE REVIEW

**Comment by PRMerger-2** [comment]
@mrwalters1988 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by ckittel — APPROVED** [review]

**Comment by ckittel** [comment]
#sign-off

(Queue the "only the owner" message :))

**Comment by PRMerger-2** [comment]
@ckittel: I'm sorry - only the author of this article, @mosabami, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger7** [comment]
@ckittel: I'm sorry - only the author of this article, @mosabami, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ckittel** [comment]
@jborsecnik can we merge before today's publish?  Thanks!

**Comment by jborsecnik** [comment]
Merged.

-jb

**Pull request merged**
