### PR TITLE
Updated Azure Container Apps status to GA

### PR DESCRIPTION
**Pull request by dariagrigoriu**
Updated Azure Container Apps status to GA and aligned branding.

### CODE REVIEW

**Comment by Court72** [comment]
@alicejgibbons 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by EdPrice-MSFT — APPROVED** [review]
Looks good!

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger4** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger-2** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Review by Court72 — APPROVED** [review]

**Pull request merged**
