### PR TITLE
Update event-processing.yml

### PR DESCRIPTION
**Pull request by bricewmiller**
Adding fcp and cse for CSE's contribution, to monitor article

#sign-off

### CODE REVIEW

**Comment by PRMerger20** [comment]
@bricewmiller : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by bricewmiller** [comment]
#sign-off

**Comment by PRMerger12** [comment]
@bricewmiller: I'm sorry - only the author of this article, @doodlemania2, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
@bricewmiller This pull request was opened in the public repo. Did you mean to create it in the private repo?

**Comment by bricewmiller** [comment]
Yes I did, sorry.

Brice Miller (He/Him) | Program Manager II | PMO GPS
Commercial Software Engineering (CSE)
***@***.******@***.***> | +1 907-953-1122

**Comment by ktoliver** [comment]
It looks like a replacement pull request was created in the private repo, so we'll close this PR. Thanks.

**Pull request closed without merging**
