### PR TITLE
Line 143 - About support of "AZSQL Managed Instance"

### PR DESCRIPTION
**Pull request by VikramPendse**
Linne 143 says "Currently, Data Migration Assistant doesn't support assessment for migrating to an Azure SQL Database Managed Instance. As a workaround, Contoso uses SQL Server on an Azure VM as the supposed target for the assessment." However, current DMA tool (Windows App) shows an option of "Azure SQL Managed Instance" when we select "Assessment" as Project Type.
AZSQLMG

### CODE REVIEW

**Comment by PRMerger14** [comment]
@VikramPendse : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@chbain : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by chbain** [comment]
@BrianBlanchard Corrected syntax on line 143. Please review for accuracy.

**Comment by doodlemania2** [comment]
Addressed internally and will be updated soon!

**Pull request closed without merging**
