### PR TITLE
Update windows-virtual-desktop.md

### PR DESCRIPTION
**Pull request by msdnguy**
Added info regarding Defender and the NetBios Limitation

### CODE REVIEW

**Comment by PRMerger6** [comment]
@msdnguy : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by doodlemania2** [comment]
@christiaanbrinkhoff - can you look at this with us?

**Comment by doodlemania2** [comment]
Closed per author as changes are pending that would conflict with this proposal.

**Comment by msdnguy** [comment]
Interesting- can you share the changes that conflict.  I was just expanding on the limitation.  Are we planning on backfilling host pool numbering?  Looking through the PRs that are open I did not see anything.

**Pull request closed without merging**
