### PR TITLE
Update analytical-data-stores.md

### PR DESCRIPTION
**Pull request by arindam0310018**
This Change is requested as it is marked Yes in https://docs.microsoft.com/en-us/azure/architecture/data-guide/relational-data/online-analytical-processing

### CODE REVIEW

**Comment by Jak-MS** [comment]
@EdPrice-MSFT - Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by arindam0310018** [comment]
Hello Team,
Is there any update on the PR ?

Regards, Arindam Mitra

**Comment by Jak-MS** [comment]
@EdPrice-MSFT - nudge

**Review by EdPrice-MSFT — APPROVED** [review]
Good update!

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Pull request merged**
