### PR TITLE
Update gitflow-branch-workflow.md

### PR DESCRIPTION
**Pull request by CalvinAllen**
Remove what looks to be rogue syntax highlighting blocks

### CODE REVIEW

**Comment by PRMerger6** [comment]
@CalvinAllen : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by SydneyUniLibrary-Jim** [comment]
I just opened issue #1964 about this page about it being a copy from [Atlassian](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow).

**Comment by ktoliver** [comment]
#sign-off

**Comment by PRMerger15** [comment]
@ktoliver: I'm sorry - only the author of this article, @UmarMohamedUsman, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
