### PR TITLE
[WIP] AKS-ACI Virtual Node Burst Capability

### PR DESCRIPTION
**Pull request by shubhammicrosoft1**
AKS-ACI Virtual Node Burst Capability PR for the Virtual Node

@mosabami @ckittel @bahramr @alex-lee-microsoft

### CODE REVIEW

**Review by ckittel — CHANGES_REQUESTED** [review]
Please reach out to me today on Teams, we need to get this moved into a different repo before we proceed. I didn't realize you were this close to publishing, or I would have let you know the process. Also, we need a TOC entry. I'll work with you today to get this in the contribution pipeline, and then you can help the others working on this area.

**Comment by ckittel** [comment]
@shubhammicrosoft1 -- cool to see additional progress.  Can you follow the instructions in the AKS Day-2 Operations Guide Contribution document that Ayo and I created for you and the team?  You can get this moved over to the correct repo, and get the contribution form filled out.  Thanks!  If you are not sure about what I mean here, ping me on Teams and I'll point you to the instructions.

**Comment by ckittel** [comment]
@mosabami  Any chance we can get this moved into the right repo while you're continuing to do your draft PR?  That way you get build validation and preview of the results.  It can stay in draft, etc.  But would be good to get it out of the public repo here.  It's basically the only PR just hanging out. :)  Lonely out here. _chuckle_

**Comment by shubhammicrosoft1** [comment]
Hi @ckittel , please let me know - i can move this across to correct repo

**Comment by ckittel** [comment]
> Hi @ckittel , please let me know - i can move this across to correct repo 

Yes, please follow the contributor guide for AAC contributions, which involves submitting the contribution form and submitting your draft as a PR against the internal repo or via Word. Thanks.

**Comment by ckittel** [comment]
Closed, moved to https://github.com/MicrosoftDocs/architecture-center-pr/pull/5752

**Pull request closed without merging**
