### PR TITLE
Typo "Postgres Hyperscale"→"PostgreSQL Hyperscale"

### PR DESCRIPTION
**Pull request by hyoshioka0128**
https://docs.microsoft.com/en-us/azure/architecture/guide/multitenant/approaches/storage-data
https://github.com/MicrosoftDocs/architecture-center/blob/main/docs/guide/multitenant/approaches/storage-data-content.md
#PingMSFTDocs

### CODE REVIEW

**Comment by Court72** [comment]
#label:"aq-pr-triaged"

**Review by EdPrice-MSFT — APPROVED** [review]
Looks good

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger10** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
