### PR TITLE
Update digital-media-video-content.md

### PR DESCRIPTION
**Pull request by IngridAtMicrosoft**
I updated the links in this doc to the correct version of Azure Media Services.

### CODE REVIEW

**Comment by IngridAtMicrosoft** [comment]
#sign-off

**Comment by IngridAtMicrosoft** [comment]
@EdPrice-MSFT please review these changes.

**Comment by IngridAtMicrosoft** [comment]
@BryanLa I have made the edits that John requested.

**Comment by jborsecnik** [comment]
@EdPrice-MSFT, 

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by EdPrice-MSFT — APPROVED** [review]
Looks good! We keep the intro very short (for business reasons). But we've got the docs link in the intro now, and the full text is in the next steps, where we feature the documentation links. 

Great updates.

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Pull request merged**
