### PR TITLE
Removed an inaccurate SLA quoting a 20 minute restore time.

### PR DESCRIPTION
**Pull request by joannapod**

### CODE REVIEW

**Comment by PRMerger15** [comment]
@joannapod : Thanks for your contribution! The author(s) have been notified to review your proposed change. @MikeWasson

**Comment by ktoliver** [comment]
Note that publishing in this repository is suspended until Tuesday, May 19. Merging will resume at 7:00 AM PT Tuesday. Authors can still review and sign off on PRs during this time. **Please do not merge the PR.** Thanks. 

@tfosmark

**Comment by doodlemania2** [comment]
@ktoliver - are you sure we're frozen in the AAC repo? We were supposedly excluded from the freeze. Just wanting to confirm.

**Comment by ktoliver** [comment]
> are you sure we're frozen in the AAC repo? We were supposedly excluded from the freeze. Just wanting to confirm.

Discussed in email 👍

**Comment by tfosmark** [comment]
Update: regular publishing and PR Review can resume here after 5pm (PT) today. 

Thanks!

**Comment by ktoliver** [comment]
@doodlemania2 @alexbuckgit Whenever this PR is reviewed (and if approved), we can merge it. 👍

**Comment by ktoliver** [comment]
Thanks @doodlemania2

**Pull request merged**
