### PR TITLE
Updating ownership

### PR DESCRIPTION
**Pull request by MatchaMatch**

### CODE REVIEW

**Comment by jborsecnik** [comment]
@tophpalmer, 

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by alexhart11** [comment]
@jborsecnik This PR should have been created in the private repo (architecture-center-pr). How do we handle this currently?

**Comment by jborsecnik** [comment]
> @jborsecnik This PR should have been created in the private repo (architecture-center-pr). How do we handle this currently?

Hi. Can you submit these changes in a PR to the private repo? Thanks.

**Comment by jborsecnik** [comment]
> > @jborsecnik This PR should have been created in the private repo (architecture-center-pr). How do we handle this currently?
> 
> Hi. Can you submit these changes in a PR to the private repo? Thanks.

Or, @tophpalmer can approve it for merge here.

**Review by alexhart11 — APPROVED** [review]

**Comment by alexhart11** [comment]
I just approved this for merge, if that's OK.
#sign-off

**Comment by alexhart11** [comment]
@tophpalmer
Can you please sign off? Thanks

**Review by EdPrice-MSFT — APPROVED** [review]
Looks good!

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by Court72** [comment]
I'll merge based on PnPFTEs' sign-off. Thanks!

**Pull request merged**
