### PR TITLE
Use AuthenticationSchemes instead

### PR DESCRIPTION
**Pull request by vanillajonathan**
`ActiveAuthenticationSchemes` is obsolete. Use `AuthenticationSchemes` instead.

### CODE REVIEW

**Review by ckittel — APPROVED** [review]
lgtm

**Comment by Court72** [comment]
@ckittel 

Thanks for the review! If the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by ckittel** [comment]
#sign-off

**Comment by ckittel** [comment]
That never works for me out here in the public repo, @Court72  -- but done anyway :)

**Pull request merged**
