### PR TITLE
Align HTTP status code in description to diagram

### PR DESCRIPTION
**Pull request by hsperker**
In the solutions sequence diagram the first call to the status endpoint returns 200. The second point of the description following description mentions a 202. Those two things should be aligned.

### CODE REVIEW

**Comment by ShannonLeavitt** [comment]
@EdPrice-MSFT – Can you review the proposed changes? IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"

**Review by EdPrice-MSFT — APPROVED** [review]
Looks good. Thanks!

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger15** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
