### PR TITLE
Update azure-digital-twins-builder-content.md

### PR DESCRIPTION
**Pull request by jameshkramer**
Fix contributor link to LinkedIn.com..

### CODE REVIEW

**Comment by jameshkramer** [comment]
This fixes a bad contributor link to linkedin.com.

#sign-off

**Comment by PRMerger5** [comment]
Invalid command: '#sign-off'. Only the assigned author of one or more file in this PR can sign off. @

**Comment by jameshkramer** [comment]
@MicrosoftDocs/apex-docs-pr-reviewers 

The PR requires a human reviewer. Sending this comment is all I could think of to do. Please let me know the proper procedure.

Thanks, Jim

**Comment by Jak-MS** [comment]
@jameshkramer - thanks for fixing the link!

**Review by Jak-MS — APPROVED** [review]
simple fix

**Pull request merged**
