### PR TITLE
add reference to alternative architecture that levergages AzureML SDK

### PR DESCRIPTION
**Pull request by georgeAccnt-GH**

### CODE REVIEW

**Comment by PRMerger6** [comment]
@georgeAccnt-GH : Thanks for your contribution! The author, @njray, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @MikeWasson - Could you review the proposed changes? I don't find the listed author in the GitHub **Assignees** option. Thanks.

**Comment by PRMerger13** [comment]
@georgeAccnt-GH : Thanks for your contribution! The author, @njray, has been notified to review your proposed change.

**Comment by MikeWasson** [comment]
Looks good, thanks

#sign-off

**Comment by PRMerger8** [comment]
@MikeWasson: I'm sorry - only the author of this article, @njray, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by MikeWasson** [comment]
(I'm the content manager for this content)

**Comment by PRMerger16** [comment]
@GitHubber17 : Thanks for your contribution! The author, @njray, has been notified to review your proposed change.

**Pull request merged**
