### PR TITLE
Update Application Integration using Event Grids

### PR DESCRIPTION
**Pull request by evetsydrah**
- Changed the diagram from the previous
- Added Data Flow
- Added Components 
- Added Next Step
- Added Pricing Calculator

### CODE REVIEW

**Review by doodlemania2 — DISMISSED** [review]

**Comment by ktoliver** [comment]
Hi @evetsydrah @doodlemania2 - When I view the SVG file in GitHub Preview, it looks like this:

image

Do you expect it to render differently (better) when it's published to the live site, or does the image need to be adjusted before merging? Thanks.

**Comment by ktoliver** [comment]
@evetsydrah Could you see the comment by @doodlemania2 at https://github.com/MicrosoftDocs/architecture-center/pull/2674#issuecomment-780895050? Thanks.

**Comment by evetsydrah** [comment]
hi @ktoliver i can see the comment, but this is something i generate directly from the visio.

**Comment by evetsydrah** [comment]
hi @ktoliver , i will update the diagram to be bigger and central then upload in another commit.

**Comment by evetsydrah** [comment]
Hi @ktoliver , let me know if the latest diagram is better

**Comment by evetsydrah** [comment]
Hi @ktoliver and @doodlemania2 , i had updated the svg and just want to ensure you guys see that and reviewed

**Comment by doodlemania2** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@doodlemania2: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Review by ktoliver — APPROVED** [review]

**Pull request merged**
