### PR TITLE
Multiple updates

### PR DESCRIPTION
**Pull request by svchandramohan**
Added Maria DB link. Modified Azure SQL Datawarehouse to Synapse Analytics (updated the links). Added Azure Databricks link. Updated links under See Also to more recent articles. Removed references to Cortana Intelligence Suite. Is Data Lake Analytics required? The doc pointing to service comparison also needs to be edited to add MariaDB

### CODE REVIEW

**Comment by PRMerger17** [comment]
@svchandramohan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@EdPrice-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by EdPrice-MSFT — DISMISSED** [review]
Great updates

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger12** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @doodlemania2, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger12** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Revisions validated in a test PR in the private repo.

**Pull request merged**
