### PR TITLE
Update select-features.md

### PR DESCRIPTION
**Pull request by jasonhorner**
person correlation changed this was a typo...   added common abbreviations

### CODE REVIEW

**Comment by PRMerger16** [comment]
@jasonhorner : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@EdPrice-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by EdPrice-MSFT — APPROVED** [review]
Changes are good.

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger17** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @marktab, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by marktab** [comment]
#sign-off

**Review by marktab — APPROVED** [review]
These changes are ok -- I'm going to come behind this pull request to fix some other wording.

**Comment by marktab** [comment]
@jasonhorner I remember you from SQL Saturday Chicago

**Pull request merged**
