### PR TITLE
removing the VM scale requirement for VDC

### PR DESCRIPTION
**Pull request by bennage**
We think that using the number of VMs can be misleading in both directions.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@bennage : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by bennage** [comment]
bump

**Comment by bennage** [comment]
bump

**Comment by PRMerger20** [comment]
@BrianBlanchard : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by BrianBlanchard** [comment]
#sign-off

**Pull request merged**
