### PR TITLE
Adding section on Managed Apache Cassandra

### PR DESCRIPTION
**Pull request by TheovanKraay**

### CODE REVIEW

**Comment by PRMerger9** [comment]
@TheovanKraay : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@TheovanKraay : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@TheovanKraay : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by arsenvlad — APPROVED** [review]
LGTM

**Review by arsenvlad — DISMISSED** [review]

**Comment by arsenvlad** [comment]
#sign-off

**Comment by PRMerger12** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by ktoliver — APPROVED** [review]

**Pull request merged**
