### PR TITLE
Added new articale

### PR DESCRIPTION
**Pull request by hangwan97**
Comparing Java Applications Hosting options on Azure

### CODE REVIEW

**Comment by ckittel** [comment]
@hangwan97 -- As a MSFT FTE, can you please reach out to us.  We'd like to make sure this is brought in through the internal process.

**Comment by ckittel** [comment]
#please-close

**Comment by ckittel** [comment]
Reopened: MicrosoftDocs/architecture-center-pr#7829

**Comment by hangwan97** [comment]
> @hangwan97 -- As a MSFT FTE, can you please reach out to us. We'd like to make sure this is brought in through the internal process instead of the public repo. We won't merge this via the public repo. Ping me on Teams and I can help out.

Sure, will do. Thanks for the review

**Pull request closed without merging**
