### PR TITLE
Added Services to create Landing Zone

### PR DESCRIPTION
**Pull request by aruanurag**
Azure : Blueprint
AWS: ControlTower

### CODE REVIEW

**Comment by PRMerger7** [comment]
@aruanurag : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by EdPrice-MSFT — APPROVED** [review]
Looks great.

**Review by EdPrice-MSFT — APPROVED** [review]
Looks great.

**Comment by PRMerger14** [comment]
@EdPrice-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
