### PR TITLE
Anomaly Detector 

### PR DESCRIPTION
**Pull request by ChandreshAwasthi**
Updated Anomaly detector diagram with recommended naming convention

### CODE REVIEW

**Comment by doodlemania2** [comment]
@evetsydrah - agreed, can you tweak that image some?

**Comment by ktoliver** [comment]
> @evetsydrah Steve Chow FTE - agreed, can you tweak that image some?

I think this comment was meant for a different pull request - https://github.com/MicrosoftDocs/architecture-center/pull/2672. I'll post it there.

@doodlemania2 Have you had a chance to look at this PR?

**Comment by ktoliver** [comment]
@doodlemania2 @ChandreshAwasthi The SVG file in this PR doesn't look right in GitHub Preview either:

image

@ChandreshAwasthi Can you see if you can fix it? Thanks.

**Comment by ChandreshAwasthi** [comment]
Is there a tool you use to convert images to SVG? I tried an online tool and thats what it returned

**Comment by doodlemania2** [comment]
The SVG looks okay, maybe just see if you can crop it some??

**Comment by ChandreshAwasthi** [comment]
@ktoliver you helped convert png to svg on my previous PR. I appreciate your help in converting this one to SVG with appropriate cropping as I am not sure how to do that.

**Comment by ktoliver** [comment]
> @ktoliver Kristine Toliver (Aquent LLC) Vendor you helped convert png to svg on my previous PR. I appreciate your help in converting this one to SVG with appropriate cropping as I am not sure how to do that.

Hi @ChandreshAwasthi Oh? I don't recall... I don't know much about working with SVG files. Perhaps the PM/content team has some guidelines or standards, because it uses SVG files widely in the content? 

I looked at some SVG files in the repo, and some have transparent backgrounds, and others have white backgrounds. I don't want to step on any standards that might be in place, but it _seems_ like you'd want a file that is intended to be downloaded to have a non-transparent background, and you'd want it to be larger than what appears in the article, if the idea is to have an image that is easier for the user to study for guidance in their own situation.

You could look in the Microsoft-internal contributor guide (I didn't see much there), or you could contact the Docs support channel in Teams. I'd probably do the latter.

**Comment by ktoliver** [comment]
> @ktoliver Kristine Toliver (Aquent LLC) Vendor you helped convert png to svg on my previous PR. I appreciate your help in converting this one to SVG with appropriate cropping as I am not sure how to do that.

Hi @ChandreshAwasthi Perhaps the PM/content team has some guidelines or standards, because it uses SVG files widely in the content? I don't have any direct experience, although I know there are many options for file conversion.

I looked at some SVG files in the repo, and some have transparent backgrounds, and others have white backgrounds. You'd want to follow any standards that might be in place for the content, but it seems like you'd want a file that will be downloaded to have a non-transparent background, and you'd want it to be larger than what appears in the article. 

You also might contact the Docs support channel on Teams.

**Comment by doodlemania2** [comment]
We have a new team in house that is working on the diagrams and making sure they are all up to snuff. Let's #sign-off for now and we'll come back around and make that image gooder (my favorite fake word)

**Comment by PRMerger16** [comment]
@doodlemania2: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Review by doodlemania2 — APPROVED** [review]

**Pull request merged**
