### PR TITLE
Update well-architected-framework-azure-firewall.md

### PR DESCRIPTION
**Pull request by christiankuhtz**
correcting bug per PG request

### CODE REVIEW

**Comment by Jak-MS** [comment]
@rohilla-shweta 

Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by christiankuhtz** [comment]
@Jak-MS Shweta doesn't own this area anymore as I own Networking now.  How can we update? :)

**Review by Jak-MS — APPROVED** [review]
accepting @christiankuhtz as new article owner according to Teams chat

**Comment by christiankuhtz** [comment]
@Jak-MS thank you!

**Pull request merged**
