### PR TITLE
docs: added profisee purview docs to ref arch

### PR DESCRIPTION
**Pull request by pdevito3**
Submitting new docs to review how to integrate Profisee MDM with Purview

### CODE REVIEW

**Comment by ktoliver** [comment]
Hi @pdevito3 - Thanks for your pull request. A member of the content team will review it.

**Comment by pdevito3** [comment]
@ktoliver just wanted to double check there's no action items pending from us here?

**Comment by EdPrice-MSFT** [comment]
Very cool! We're reviewing it. Let's leave this PR open through the review process.

**Comment by skabou** [comment]
Engineering review looks good.  Separately, just noticed a few typos--

"If offers a combination"

"Backed by the support of data owners and experts, they armed to address data quality issues"

"Inability to analyzing customer data across systems"

**Comment by pdevito3** [comment]
Nice, thanks. Will knock those out momentarily.

**Comment by EdPrice-MSFT** [comment]
Cool. Thanks @pdevito3! We will move this along, with your updates, to our editorial team for the final copy edit.

Thanks!

**Comment by pdevito3** [comment]
@EdPrice-MSFT any updates on this? let me know if there's any action items pending on our front

**Comment by EdPrice-MSFT** [comment]
@pdevito3 - We have it in our editor's backlog.

**Review by EdPrice-MSFT — APPROVED** [review]
We finished our editing pass on this external contribution (with internal MS review and sponsorship). 

Thank you for this excellent contribution!

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger17** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @pdevito3, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by pdevito3** [comment]
#Sign-Off

**Comment by PRMerger18** [comment]
Only Microsoft employees can sign off on PRs. Your PR will be routed for review.

**Pull request merged**
