### PR TITLE
Microservices Design : Container Orchestration

### PR DESCRIPTION
**Pull request by veerashayyagari**
Document explaining the challenges faced with managing containers at scale, how container orchestration can help and what are the offerings in Azure that help with leveraging container orchestration.

### CODE REVIEW

**Comment by tfosmark** [comment]
Email sent to PnP team for review of the new content.

**Comment by EdPrice-MSFT** [comment]
This is in internal review for our production pipeline. We'll replace/close the PR when the new one is ready. Thanks!

**Comment by ckittel** [comment]
Do we have an internal PR for this yet @EdPrice-MSFT?  If so, shoot that over on Teams.  Thanks.

**Comment by veerashayyagari** [comment]
Submitted a separate PR on the private repo. Closing this pull request.

**Comment by PRMerger9** [comment]
Microsoft authors of articles need to make updates through the private repository so the updates can be staged and validated by the current validation rules. After you review staging and fix all validation issues, you can add the sign-off comment to let the PR reviewers know the updates are ready to be merged.It's easy to access the private repo version of your articles in GitHub. Just add -pr to the URL, as follows: 
 Public repo URL: https://github.com/MicrosoftDocs/azure-docs 
 Private repo URL: https://github.com/MicrosoftDocs/azure-docs-pr 
 We have closed this pull request. Please resubmit the updates through the private repo. For more information, [see the contributor guide].(https://docs.microsoft.com/en-us/contribute/)

**Pull request closed without merging**
