### PR TITLE
Minor punctuation fix

### PR DESCRIPTION
**Pull request by naveedkharadi**
Minor punctuation fix - removed a comma

### CODE REVIEW

**Comment by PRMerger10** [comment]
@naveedkharadi : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@EdPrice-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by EdPrice-MSFT — APPROVED** [review]
The comma was necessary, but the quotes weren't. So we're moving to italics instead. Great catch. Thanks!

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Pull request merged**
