### PR TITLE
Update services.md

### PR DESCRIPTION
**Pull request by cjnova**
Compute Section. Remove references to CloudSimple and updated info for Azure VMWare Solution

### CODE REVIEW

**Comment by PRMerger9** [comment]
@cjnova : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@cjnova : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@EdPrice-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by EdPrice-MSFT — APPROVED** [review]
Great update!

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Pull request merged**
