### PR TITLE
Updates on Cosmos DB

### PR DESCRIPTION
**Pull request by markjbrown**
Added a section on Cosmos DB RPO and RTO.
Updated the section on cost considerations to account for autoscale.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@markjbrown : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by josevarela** [comment]
#sign-off

**Comment by PRMerger14** [comment]
@josevarela: I'm sorry - only the author of this article, @doodlemania2, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ckittel** [comment]
@ktoliver ready to merge.  Thanks.

**Pull request merged**
