### PR TITLE
New: Design Pattern:  The Resource Conveyor - An Efficient Resource Management Pattern

### PR DESCRIPTION
**Pull request by ubiquio**
#### Summary, scope, and intent of this PR

This PR introduces the Resource Conveyor Pattern, a new design pattern aimed at efficiently managing the lifecycle of long-running, non-managed external resources such as browser instances, external APIs, or system libraries that degrade over time. The pattern ensures that resources are preloaded, actively utilized, and safely offloaded in a conveyor-style rotation, mitigating performance degradation and ensuring system stability.

This pattern is designed to fill a gap in existing cloud architecture patterns, addressing the specific problem of resource exhaustion and slowdowns due to long-term usage.

#### Links to any related work item(s) or supporting detail

inline in the Resource Conveyor md file (justification md)

<details><summary>AFTER YOUR PR HAS BEEN CREATED, expand this section for tips and additional instructions.</summary>
These are common guidelines for contributions across the repos managed by the Azure patterns & practices (PnP) content team. Some repositories may have additional specific requirements that are not listed here.   

## Guidance for all contributors  
  
| Topic | Guidance |
| ----------| ------------ |
| **Draft PR** | If your PR will be a work-in-progress for more than a day or two, select the **Convert to draft** link in the upper right of the page (under **Reviewers**) to change it to a draft. For future reference, you can also do this using the **Create pull request** button drop-down during PR creation. | 
| **ms.date metadata** | <ul><li>Don't update an article's "ms.date" metadata property unless you've done a **full freshness review** of the content. A full freshness review includes changes required to correct or improve the **full** technical accuracy of the article.</li><li>Don't update "ms.date" if you're doing targeted changes to improve non-technical aspects of the article, such as editorial quality, art improvements, article template alignment, etc.</li><li>If you've changed any "ms.date" properties for work that wasn't part of full review for freshness, please reset them to their previous value.</li></ul> | 
| **Placement and linking** | If you're creating a new article or articles, include updates to the related TOC.yml file to propose where the article(s) should be placed. Also consider other places within the document set where it would be beneficial to cross-reference and link to your new article(s). | 
| **PR build** | After you open your PR, and for each successive commit that you push to your branch, the publishing platform will run validation on the files in your pull request. A summary of the build results for each file will be inserted inline into your pull request, which includes any build suggestions/warnings/errors. PRs cannot be merged until all build errors and most warnings are resolved. |
| **Publishing** | Following a successful merge, most repos publish to the live site about once per (business) day. |
| **Additional resources** | <ul><li>[learn.microsoft.com contributor guide](https://review.learn.microsoft.com/help/contribute/?branch=main)</li></ul>
  
## Additional guidance for private repos and internal contributors  

| Topic | Guidance | 
| ----------| ------------ | 
| **PR size** | If your PR is more than ~5 lines of changes, or you'd like for the changes to go through editorial or larger review, open a contribution request at <https://aka.ms/contribution> and include a link to the PR in response #8. Once it's processed, you'll be notified of the next steps.  |
| **PR title prefix** | Select the **Edit** button to the right of the PR title if you need to revise it. The following prefixes are reserved for specific contribution types:<br/><br/><ul><li>**[Quality Check]** - maintenance work related to content quality (edit passes, art improvements, template alignment)</li><li>**[LinkFix]** - recurring/adhoc PRs to correct link URLs</li><li>**[Pipeline]** - new/updated contributor success pipeline content</li><li>**[WIP]** - a work-in-progress draft requiring several days/weeks</li></ul> |
| **PR preview** | Following successful build of your PR, publishable files will also include **Preview URL** links to staged previews of your new/updated articles. Be sure to review these for verification of your intended contributions, or to send to other internal contributors for review. |
| **PR sign-off (public repo)** | If an article you own is updated in a public repo PR, you are responsible for sign-off. You will be automatically notified via email. The PR will not be merged until you've had a chance to review and sign-off. |
| **PR sign-off (private repo)** | After you've completed your proposed changes, addressed build warnings, and completed all review work, you can begin the sign-off process for review and merge:<br/><br/><ol><li>If your PR is in draft mode, remove "[WIP]" from the title and select **Ready for review** button at the bottom of the PR.</li><li>Enter "#sign-off" in a new comment. This comment indicates that **you're confident the work meets or exceeds Microsoft's standards for publication**, and will trigger the review process.</li><li>Your PR may be selected for initial review by the PnP content team. Following PnP review, you may receive questions or requests for additional changes. You should have initial feedback from PnP review within a few business days. If you have an urgent request or need to contact the team, please mention `@MicrosoftDocs/patterns-and-practices-team-pr-reviewers` in your PR and someone will get back to you. After the Azure patterns & practices content review is complete, a `PnP #sign-off` will be added.</li><li>Final review/merge is done by the PR review team. The PR team may also respond with feedback, categorized as "Blocking" (requires action from you), or "Non-blocking" (to be addressed in a future PR).</li></ol> |
| **Additional resources** | <ul><li>[learn.microsoft.com internal contributor guide](https://review.learn.microsoft.com/help/contribute/?branch=main)</li><li>Authoring templates: [architecture-center-pr](https://review.learn.microsoft.com/help/contribute/architecture-center/templates/sample-solution-templates?branch=main), [well-architected-pr](https://review.learn.microsoft.com/help/contribute/global-waf-template?branch=main)</li><li>To contact the Azure patterns & practices team use [e-mail](mailto:cact-pr-reviewers@microsoft.com?subject=Help%20with%20pull%20request), or @mention our GitHub team in your PR comments using: `@MicrosoftDocs/patterns-and-practices-team-pr-reviewers`</li></ul>
</details>

### CODE REVIEW

**Comment by ckittel** [comment]
You'll need to find a Microsoft FTE that can help sponsor and take ownership of this article.  At this time, we cannot take public contributions for new articles without a Microsoft FTE to be assigned as a durable owner.  That Microsoft FTE can then open a work item with us at https://aka.ms/contribution to kick off the process.

**Comment by Jak-MS** [comment]
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by ubiquio** [comment]
> You'll need to find a Microsoft FTE that can help sponsor and take ownership of this article. At this time, we cannot take public contributions for new articles without a Microsoft FTE to be assigned as a durable owner. That Microsoft FTE can then open a work item with us at https://aka.ms/contribution to kick off the process.

thank you @ckittel.
please advise on how to obtain an MS sponsor?
I have no connections with anyone from MS

**Comment by ckittel** [comment]
Usually outside contributors use existing established relationships.  Since you're starting from scratch to build a trusted relationship, maybe attending some user group meetings with cloud solution architects that attend? Going to training sessions lead by Microsoft employees? LinkedIn searching? Reaching out to related blog posts authors on the Microsoft tech community?

Once you have a point of contact, the process is pretty straight forward.  But durable Microsoft employee ownership of the article is non-negotiable.  We can keep the PR open while you make connections or you can close and reopen it after a connection is established.  I will say, that if there is no motion in about a week, we'll close it just out of routine.  You can always reopen later.

**Comment by ubiquio** [comment]
@ckittel got it!  Thanks for the info

**Comment by ubiquio** [comment]
Having a hard time finding a sponsor, there are over a thousand members in this Git, perhaps some of them can review and "sponsor" The Resource Conveyor?  It's kind of strange that one needs to demonstrate relationship-building with an MS insider before his idea can be reviewed..  Should merit of ideas be subject to nepotism?

**Comment by ckittel** [comment]
Sorry to hear you are struggling find any support to take durable ownership of the article and its long-term maintenance. I'll close the PR for now (unless I misunderstood your declaration). If you do establish a relationship with a durable owner we can proceed to collaborate on this proposal.

#please-close

**Comment by ubiquio** [comment]
@ckittel  I was not interested in taking ownership of any article I was only interested in adding my design pattern to the list as I believe it would benefit a lot of pros.  And instead of getting a committee to review my publication for its merits, I was deferred to a relationship budling excursion.  And when I pointed out how awkward and even unjust this directive is, my PR was simply closed.. Perhaps you can direct me to a team or an individual who can review my proposal instead of just dismissing it.  It's not like you have a thousand "new design pattern" applicants knocking on you door..

**Comment by ckittel** [comment]
The policy of named, durable ownership by a Microsoft employee is a requirement for publishing an article in the Azure Architecture Center. We get contributions from the community a few times a year and durable ownership is established by the author for continuity of maintenance. But without that responsible Microsoft individual being established, we simply cannot continue.

**Comment by ubiquio** [comment]
@ckittel  do  you have any contact in MS who could potentially sponsor my effort?

**Comment by ckittel** [comment]
I unfortunately don't have a reddy recommendation of a point of contact. I'll think on it over the next few business days and if anyone comes to mind, I'll let you know by tagging them in this conversation.

I'd suggest searching on LinkedIn for a potential point of contact in the meantime. Maybe someone posted something adjacent to this topic that you can collaborate with. Maybe you can post something on LinkedIn and see what Microsoft employees engage with your post - you could even put out a request for partnership out there!

**Comment by ckittel** [comment]
Great! Boosted.

**Pull request closed without merging**
