### PR TITLE
Remove en-us for build to validate

### PR DESCRIPTION
**Pull request by ckittel**

### CODE REVIEW

**Comment by PRMerger15** [comment]
@ckittel : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ckittel** [comment]
#sign-off

**Comment by PRMerger15** [comment]
@ckittel: I'm sorry - only the author of this article, @doodlemania2, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ckittel** [comment]
@doodlemania2 this will unblock a PR on the `-pr` side of this, if you can approve/review.  Thanks :)

**Comment by doodlemania2** [comment]
#sign-off

**Pull request merged**
