### PR TITLE
updated document semantics

### PR DESCRIPTION
**Pull request by raj-microsoft**
Added more clarity to the semantics of the document and a section on how to **deploy the scenario**

### CODE REVIEW

**Comment by alexhart11** [comment]
@EdPrice-MSFT Please review and sign-off. Thanks

**Review by EdPrice-MSFT — APPROVED** [review]
Great updates.

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger15** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Review by ktoliver — APPROVED** [review]

**Pull request merged**
