### PR TITLE
Linking to libraries that support the pattern

### PR DESCRIPTION
**Pull request by udidahan**
As was already accepted in #3609.

### CODE REVIEW

**Comment by ckittel** [comment]
#sign-off

**Comment by jborsecnik** [comment]
@mSarts, 

Can you review the proposed changes? If someone else should, please advise.

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by mSarts** [comment]
@alexhart11 Please review the thread above.

**Comment by alexhart11** [comment]
#sign-off

**Comment by udidahan** [comment]
Hey folks, any chance of getting this moving again? Thanks :)

**Comment by ckittel** [comment]
@JanetCThomas / @alexhart11 - can you find out why this is being held up?  We've got multiple CACT reviews done, just PR merger is pending.

**Review by jborsecnik — APPROVED** [review]

**Comment by jborsecnik** [comment]
They delay is because this is in the public repo, so it travels a different process path. But I was able to add myself as a reviewer and approve/merge.

**Comment by jborsecnik** [comment]
@ckittel  - I will keep an eye on this issue in case any process adjustment is needed on our part (PR review team).

**Comment by udidahan** [comment]
Thanks very much everyone.

Process-wise, should I have done anything differently on my end?

**Pull request merged**
