### PR TITLE
Update networking.md

### PR DESCRIPTION
**Pull request by kobile70**
add the AWS NAT gateway corresponding service on Azure

### CODE REVIEW

**Comment by PRMerger9** [comment]
@kobile70 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
Microsoft authors of articles need to make updates through the private repository so the updates can be staged and validated by the current validation rules. After you review staging and fix all validation issues, you can add the sign-off comment to let the PR reviewers know the updates are ready to be merged.It's easy to access the private repo version of your articles in GitHub. Just add -pr to the URL, as follows: 
 Public repo URL: https://github.com/MicrosoftDocs/azure-docs 
 Private repo URL: https://github.com/MicrosoftDocs/azure-docs-pr 
 We have closed this pull request. Please resubmit the updates through the private repo. For more information, [see the contributor guide].(https://docs.microsoft.com/en-us/contribute/)

**Review by EdPrice-MSFT — APPROVED** [review]
Great update

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger16** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @kobile70, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
Hi @EdPrice-MSFT - Metadata and article ownership should be changed only in the private repo, per the internal contributor guide. Could you go ahead and create a pull request in the private repo to make all the metadata changes you'd like to see in AAC articles?

We're not intended to merge PRs in the public repo in which contributors change article ownership. We'll merge this one because we can confirm the identity and Microsoft affiliation for the contributor. 

Before we merge, *could you verify that you want to change the metadata author attribute to `kobile70`?* Thanks.

If article ownership is changed in this repo in other PRs, we'll back out those changes so you can make them in the private repo (to keep MicrosoftDocs owners content). Thanks much!

**Comment by kobile70** [comment]
Sorry for all the overhead I’ve created, I can resubmit the changes using the private repo if that help

Best Regards, Kobi

Get Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by ktoliver** [comment]
Hi @kobile70 I didn't notice that a commit was added to change article ownership. That type of metadata change should be done in the private repo, and not in the public repo. I'm checking with the lead PR reviewer and will come back to this PR shortly. Thanks :)

**Comment by ktoliver** [comment]
We'll sort it out; no worries.

**Comment by ktoliver** [comment]
@EdPrice-MSFT Hi - To update the article owner, the commit should be moved to the private repo and merged there. Let me know if you'd like the PR review team to help with this. Thanks.

**Pull request merged**
