### PR TITLE
Add vulnerability scanning of running containers

### PR DESCRIPTION
**Pull request by RicardoNiepel**
Known vulnerabilities should also be scanned in already running containers.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@RicardoNiepel : Thanks for your contribution! The author, @MikeWasson, has been notified to review your proposed change.

**Comment by doodlemania2** [comment]
@RicardoNiepel, would you be willing to update this PR to include latest and greatest from (https://docs.microsoft.com/en-us/azure/container-instances/container-instances-image-security) and elsewhere and we can get this merged in!

**Comment by doodlemania2** [comment]
On second thought, let's proceed as is, and iterate / add more to it in an upcoming sprint as it is accurate!

**Comment by MikeWasson** [comment]
#sign-off

**Pull request merged**
