### PR TITLE
Update firewall-application-gateway.md

### PR DESCRIPTION
**Pull request by asgr86**
to include note that using front door before firewall does preserve the source IP in the X-Forwarded-For header and session state.

### CODE REVIEW

**Comment by PRMerger10** [comment]
@asgr86 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by erjosito** [comment]
@asgr86 how is AFD in front of an AzFW different than the AppGW from an IP perspective? In both cases the client IP is preserved in the XFF header, right?

**Comment by asgr86** [comment]
@erjosito :   In the scenario where in we have a AppGw behind an Az Fw the document mentions that the X-Forwarded-For header is the Fw IP. however in our scenario we have Az FD that does routes traffic into multiple Az Fw's hosted in various regions and behind the Fw we have AppGw, in our case we have been able to validate that the X-Forwarded-For header that the web servers are seeing contain the client IP and not the Fw IP. ( User -> FD (Global Routing) -> AzFw -> AppGw -> IIS )

Hope this answers your question.

this detail was not captured in this document, hence wanted to update it.

**Comment by erjosito** [comment]
Nice point. Could you maybe make the text a bit more explicit, so that it is easier to get at the first read? I would suggest something like this:

...except for the option of placing Azure Firewall in front of Azure Front Door.

One interesting use case is when you are using the design with the Azure Firewall in front of the Application Gateway in your Virtual Network. As described above, the X-Forwarded-For header will not contain the client's IP address but the firewall's. A workaround is using Azure Front Door in front of the firewall to inject the client's IP address in the client request before it enters the Virtual Network.

**Comment by PRMerger6** [comment]
@asgr86 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by asgr86** [comment]
thank you @erjosito @ktoliver   i am not seeing an option to merge this branch is it something that you will take care ?

**Pull request merged**
