### PR TITLE
The main language of Stream Analytics is SQL

### PR DESCRIPTION
**Pull request by Fleid**
The flavor of SQL is "Stream Analytics query language", but the top level description is SQL.

### CODE REVIEW

**Comment by PRMerger5** [comment]
@Fleid : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
#label:"aq-pr-triaged"

**Review by EdPrice-MSFT — APPROVED** [review]
Looks good.

**Comment by EdPrice-MSFT** [comment]
Thanks, Florian!

#Sign-Off

**Pull request merged**
