### PR TITLE
Fix typo in `mlops-maturity-model-content.md`

### PR DESCRIPTION
**Pull request by alex000kim**

### CODE REVIEW

**Comment by Jak-MS** [comment]
@EdPrice-MSFT 

Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by EdPrice-MSFT — APPROVED** [review]
Great catch!

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger9** [comment]
Invalid command: '#sign-off'. Only the assigned author of one or more file in this PR can sign off. @

**Pull request merged**
