### PR TITLE
Updates Reference Architecture for Distributed training

### PR DESCRIPTION
**Pull request by msalvaris**
Updates the architecture to use AzureML

### CODE REVIEW

**Comment by PRMerger15** [comment]
@msalvaris : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by danielleodean** [comment]
@MikeWasson this is a major update given Batch AI was deprecated, if you can merge when you can that'd be great, thanks!

**Comment by jborsecnik** [comment]
@msalvaris, FTEs need to submit PRs via the private repo. Please submit these changes there.

If you need setup info:

Follow the instructions in [Set up Git repository locally for documentation](https://review.docs.microsoft.com/en-us/help/contribute/contribute-get-started-setup-local?branch=master) to link your GitHub alias with your Microsoft account. 

Then, make content contributions through the private repository so the content can be staged and validated by the current validation rules.  

Read about [working in the public repo](https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=master) for more information.  

Thank you.

**Comment by MikeWasson** [comment]
@danielleodean I'll move this PR to the private repo.

**Comment by msalvaris** [comment]
@MikeWasson I have already moved it to the private repo  https://github.com/MicrosoftDocs/architecture-center-pr/pull/140

**Comment by MikeWasson** [comment]
Opened MicrosoftDocs/architecture-center-pr#141

**Pull request closed without merging**
