### PR TITLE
Removed controversial section

### PR DESCRIPTION
**Pull request by omartin2010**
This causes issues because the routes in the far right VNets would not be advertised over hybrid connections (ER + VPN) which causes design issues.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@omartin2010 : Thanks for your contribution! The author(s) have been notified to review your proposed change. @telmosampaio

**Comment by Jak-MS** [comment]
@MikeWasson - wasn't sure who to assign this to since the listed author @telmosampaio isn't on the list of potential assignees. can you review or reassign? thanks.

**Comment by MikeWasson** [comment]
#sign-off

**Comment by PRMerger14** [comment]
@MikeWasson: I'm sorry - only the author of this article, @telmosampaio, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by MikeWasson** [comment]
I'm the content manager for this doc - thanks!

**Pull request merged**
