### PR TITLE
Several URLs resulting in 404 not found

### PR DESCRIPTION
**Pull request by retracement**
Have updated these with what I believe are the new (correct) intended links.

### CODE REVIEW

**Comment by PRMerger10** [comment]
@retracement : Thanks for your contribution! The author(s) have been notified to review your proposed change. @petertay

**Comment by alkohli** [comment]
@ktoliver  Not sure why this is assigned to me. I do not work on this. Thanks!

**Comment by ktoliver** [comment]
> @ktoliver Kristine Toliver (Aquent LLC) Vendor Not sure why this is assigned to me. I do not work on this. Thanks!

Alpa, please accept my apologies. I must have switched to a different browser window and looked at a file in a different pull request.

**Comment by ktoliver** [comment]
Hi @mikewasson - Could you review the proposed changes or recommend a reviewer? I don't find a Microsoft-linked GitHub user account for Peter Taylor.

**Pull request merged**
