### PR TITLE
Editbranch 

### PR DESCRIPTION
**Pull request by aajaluwa1**
Thumbnail did not update in previous PR. Reloaded URL in .yml file for updated image.

### CODE REVIEW

**Comment by PRMerger3** [comment]
@aajaluwa1 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by aajaluwa1** [comment]
3cb3661 is a duplicate of 69193f7. Both are updating the thumbnail image in the .yml file.

**Comment by jborsecnik** [comment]
@EdPrice-MSFT, if you approve this PR, does the changes need to be moved to the private repo for staging, since we don't get a preview of this article in GitHub? If so, can you do that move? Thanks.

**Comment by EdPrice-MSFT** [comment]
@jborsecnik - Well these images are in the YML metadata, so we wouldn't get a preview. For example, the Thumbnail one updates the thumbnail image shown at http://aka.ms/Architectures. 

@aajaluwa1 - We won't take this one. Sorry. I think that both those paths need to be in their current format. For the thumbnail, it needs to point to the thumbnail folder, or else it isn't going to show up. It would just show up at http://aka.ms/Architectures as no thumbnail image. So the next step would be to copy your new diagram folder into the Thumbs folder to update the Thumbs image with your new diagram. Then the associated thumbnail diagram image at http://aka.ms/Architectures would reflect our new diagram. 

In the future, can you submit PRs to the private repo? I recommend using http://aka.ms/SpineEdit to make that process smoother.

Thanks!

**Pull request closed without merging**
