### PR TITLE
Updated doc to include Synapse for integration

### PR DESCRIPTION
**Pull request by msdnguy**
changed author to bbandam in the Product team.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@msdnguy : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by bhbandam — APPROVED** [review]

**Comment by bhbandam** [comment]
#sign-off

**Review by bhbandam — APPROVED** [review]

**Review by bhbandam — APPROVED** [review]

**Review by bhbandam — APPROVED** [review]
#sign-off

**Comment by bhbandam** [comment]
#sign-off

**Comment by ckittel** [comment]
#sign-off

**Comment by PRMerger-2** [comment]
@ckittel: I'm sorry - only the author of this article, @bhbandam, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Review by ckittel — APPROVED** [review]
LGTM, thanks!

**Comment by PRMerger9** [comment]
@ckittel: I'm sorry - only the author of this article, @bhbandam, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
