### PR TITLE
Added link to Priority Queue guidance for sending commands with messaging

### PR DESCRIPTION
**Pull request by udidahan**
Simple change to add link.

### CODE REVIEW

**Review by doodlemania2 — APPROVED** [review]

**Review by doodlemania2 — DISMISSED** [review]

**Review by ktoliver — APPROVED** [review]

**Comment by PRMerger17** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by ktoliver — DISMISSED** [review]
Resolved merge conflict

**Comment by PRMerger18** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by ktoliver — APPROVED** [review]

**Comment by udidahan** [comment]
Perfect. Thanks :-)

**Pull request merged**
