### PR TITLE
Change HIPPA to HIPAA

### PR DESCRIPTION
**Pull request by SvenAelterman**
Change file names, titles, and headings

### CODE REVIEW

**Comment by PRMerger7** [comment]
@SvenAelterman : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@adamboeglin If you approve the PR--the updates look correct--the PR review team can move this to the private repo so we can verify the updates on staging and create a redirect for the renamed .MD file. Thanks.

**Comment by ktoliver** [comment]
@adamboeglin Because of a longstanding issue related to syncing between public and private architecture-center repositories, I'm not able to move the commit to the private repo like I usually do. Would you or @SvenAelterman submit this work in a new PR in the private repo? The renamed MD file needs a redirect added to the repo's redirection JSON file, and it's a good idea to check everything on staging because of the file renaming.

**Comment by SvenAelterman** [comment]
I would be happy to redo the PR, but I am not sure how to find the private repo?

**Comment by ktoliver** [comment]
Hi @SvenAelterman - To get to a Microsoft Docs private repo, add "-pr" to the repo name (true for most Microsoft Docs content repos, with only one exception that I'm aware of). For example, the private iteration here would be **architecture-center-pr**: https://github.com/MicrosoftDocs/architecture-center-pr

 Thanks!

**Comment by ktoliver** [comment]
Actually, I think the key step for getting access is in the next section in the article I linked to: [Join MicrosoftDocs organization and others](https://review.docs.microsoft.com/en-us/help/contribute/contribute-get-started-setup-github?branch=master#join-microsoftdocs-organization-and-others).

**Comment by ktoliver** [comment]
@doodlemania Would you add a redirect for the renamed file to the repo's openpublishing.redirection.json file per the quality criteria in the contributor guide? Otherwise, anyone who has the link bookmarked or embedded will get a broken link. Also, make sure when it goes live that all the images appear (they're referenced correctly). Thanks.

**Comment by ktoliver** [comment]
@doodlemania The images actually won't render, because the PR renames the image files but doesn't change the image references:

image

I'll do a PR in the private repo to fix these items.

**Comment by doodlemania2** [comment]
oh drat - thanks @ktoliver for the catch.

**Pull request merged**
