### PR TITLE
Update data-science-and-machine-learning.md

### PR DESCRIPTION
**Pull request by j-martens**
Fixing the link. cc: @rastala

### CODE REVIEW

**Comment by PRMerger17** [comment]
@j-martens : Thanks for your contribution! The author, @MikeWasson, has been notified to review your proposed change.

**Comment by Jak-MS** [comment]
Hi @j-martens - I've manually tested this and the link still isn't working (although this really should be submitted to the private repo so that validation would have caught it).  I think the reason it's not working is because it's a relative link cross-repo... but I'm not sure. 

Can you submit this to the private repo architecture-center-pr instead? That way we can using validation and staging to assess this?

Thanks.

**Comment by j-martens** [comment]
HI @Jak-MS - I didn't have permissions to the repo so i went the public route.

**Comment by Jak-MS** [comment]
Hi @j-martens - oh, i see. Sorry, I thought you'd have permissions. 

I can merge the PR and you or @MikeWasson can check to see if it's working after it goes live. (sometimes relative links work in the live articles even they don't in the GitHub view). If it still doesn't work, I'd recommend that @MikeWasson change it in the private repo.

Thanks.

**Pull request merged**
