### PR TITLE
Updated formatting and added a space

### PR DESCRIPTION
**Pull request by HJToland3**

### CODE REVIEW

**Comment by PRMerger19** [comment]
@HJToland3 : Thanks for your contribution! The author, @adamboeglin, has been notified to review your proposed change.

**Comment by HJToland3** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@HJToland3: I'm sorry - only the author of this article, @adamboeglin, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by HJToland3** [comment]
@adamboeglin, I just added a space and added bold face to two terms. Thanks!

**Comment by jborsecnik** [comment]
Verified format fixes.

**Pull request merged**
