### PR TITLE
Adding three different architectures, monitoring and observability

### PR DESCRIPTION
**Pull request by Sarah-Aly**

### CODE REVIEW

**Comment by ktoliver** [comment]
Hi @EdPrice-MSFT We'll move this commit to the private repo for automated validations and to check the updates and image references on staging. We can do that before or after you review it (or indicate if someone else would be a better resource for the content review). Thanks!

**Comment by ckittel** [comment]
@ktoliver & @EdPrice-MSFT  has this been moved over and can this PR then be closed?

**Review by v-fearam — COMMENTED** [review]
This document includes https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/serverless/event-processing
Is this document going to replace that one?

The document presents a second architecture with three options. I think it would be good to present when we should use one or another (Use case, pros, cons...), among each option and against the first architecture.

In the original architecture (first one, https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/serverless/event-processing)  The dead letter queue is a Storage Account, but in the new option are EventHub. Why? Are you expecting several errors? What is the cost impact? Some lines about that I think could be helpful.

Monitoring section is a really good addition to this new document.

After reading this document, and without still able to take a look to the deployable assets, I don’t sure if this should be a new repo o part of the same where is store the first architecture (https://github.com/mspnp/serverless-reference-implementation). We will see later on.

**Comment by ktoliver** [comment]
@ckittel @EdPrice-MSFT I'll move the commit to the private repo now. I'll post here when I have a new pull request, and then we'll close this one. The content will need to be reviewed and signed off (after I address some blocking PR review quality items that I see) in the new pull request. Thanks!

**Comment by ktoliver** [comment]
The commit has been moved to the private repository and will be reviewed and merged from there. We'll close this pull request. Thanks.

**Comment by ktoliver** [comment]
> This document includes https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/serverless/event-processing
> Is this document going to replace that one?
> 
> The document presents a second architecture with three options. I think it would be good to present when we should use one or another (Use case, pros, cons...), among each option and against the first architecture.
> 
> In the original architecture (first one, https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/serverless/event-processing) The dead letter queue is a Storage Account, but in the new option are EventHub. Why? Are you expecting several errors? What is the cost impact? Some lines about that I think could be helpful.
> 
> Monitoring section is a really good addition to this new document.
> 
> After reading this document, and without still able to take a look to the deployable assets, I don’t sure if this should be a new repo o part of the same where is store the first architecture (https://github.com/mspnp/serverless-reference-implementation). We will see later on.

I'll add these comments to the new PR, so they are factored in.

**Pull request closed without merging**
