### PR TITLE
Move Altair and PBSPro to the same line

### PR DESCRIPTION
**Pull request by doodlemania2**
Same product, different licensing. Closes https://github.com/MicrosoftDocs/architecture-center/issues/1695

### CODE REVIEW

**Comment by PRMerger14** [comment]
@doodlemania2 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@doodlemania2 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by doodlemania2** [comment]
> Honestly, I'd drop the open source project all together, since I can't find any Azure related docs for it.
> 
> How about
> 
> `[Altair PBS Works](https://web.altair.com/pbs-on-azure)`
> 
> That way it's driving specifically to Azure related docs and includes both the Altair and PBS names.

Complete #sign-off

**Comment by PRMerger6** [comment]
@doodlemania2: I'm sorry - only the author of this article, @adamboeglin, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by adamboeglin** [comment]
#sign-off

**Pull request merged**
