### PR TITLE
Changes detailed below

### PR DESCRIPTION
**Pull request by svchandramohan**
Great article!
-Some minor change suggestions
-The #Deploy the scenario has a few options that does not seem correct based on what the ARM template deploys:
 -The current ARM template only allows me to select a existing Purview account. There is no scope of creating a new one. So I have modified it accordingly. The snip showing the 
  ARM template is also incorrect at this time
 -Also, line 233 of the original document refers to Purview sizing (4, 16 CUs) which is not relevant anymore

### CODE REVIEW

**Review by EdPrice-MSFT — DISMISSED** [review]
Good updates

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger15** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Review by EdPrice-MSFT — DISMISSED** [review]
Looks good

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger12** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Review by ktoliver — APPROVED** [review]

**Pull request merged**
