### PR TITLE
Update Private Connectivity to PaaS

### PR DESCRIPTION
**Pull request by husunal**
VPC Service Controls doesn't provide a private endpoint.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@husunal : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Court72** [comment]
@EdPrice-MSFT 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"

**Review by EdPrice-MSFT — APPROVED** [review]
Looks good.

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Pull request merged**
