### PR TITLE
Fixing Intro Part

### PR DESCRIPTION
**Pull request by DixitArora-MSFT**
(AzureCXP) fixes MicrosoftDocs/architecture-center#1741

### CODE REVIEW

**Comment by DixitArora-MSFT** [comment]
@jborsecnik I am able to browse the Storage explorer link in the main doc. Also I haven't  made any change to storage explorer link. The only change I made in PR is "Large Scaler" .

**Comment by jborsecnik** [comment]
Sorry, I just pasted a comment in the wrong PR. -jb

**Comment by jborsecnik** [comment]
@MikeWasson, can you review/approve this?

**Comment by MikeWasson** [comment]
LGTM

**Pull request merged**
