### PR TITLE
new article

### PR DESCRIPTION
**Pull request by TerryLanfear**
#hold-off

### CODE REVIEW

**Comment by PRMerger6** [comment]
@TerryLanfear : Thanks for your contribution! The author, @isaiah-msft, has been notified to review your proposed change.

**Comment by TerryLanfear** [comment]
@PRMerger6 , @isaiah-msft - This article is not ready for publishing. At this time we are only staging the content for reviews.

**Comment by ktoliver** [comment]
Hi @TerryLanfear - This pull request was opened in the public repo. Do you intend to work in the private repo instead?

**Comment by TerryLanfear** [comment]
@ktoliver - Thank you, Kristine, for pointing that out. I intended to work in the private repo. What is the name of the private repo for the architecture center site? Thanks!

**Comment by Jak-MS** [comment]
Hi @TerryLanfear - the repo you want is https://github.com/MicrosoftDocs/architecture-center-pr . 

Can you close this PR when you've moved the commits to the private repo? 

Thanks!

**Pull request closed without merging**
