### PR TITLE
Update mobile section to mention App Center

### PR DESCRIPTION
**Pull request by elamalani**
Updating Mobile service section to talk about App Center

### CODE REVIEW

**Comment by PRMerger14** [comment]
@elamalani : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by elamalani** [comment]
@conceptdev please review.

**Comment by PRMerger13** [comment]
@adamboeglin : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by elamalani** [comment]
@doodlemania2 when will this PR be live on the docs?

**Pull request merged**
