### PR TITLE
Removing the parallel R sample repo

### PR DESCRIPTION
**Pull request by SvenAelterman**
It's no longer maintained, build is currently failing, and most recent update was 11 months ago.

### CODE REVIEW

**Comment by PRMerger4** [comment]
@SvenAelterman : Thanks for your contribution! The author(s) have been notified to review your proposed change. @SMBrook

**Comment by Jak-MS** [comment]
@SvenAelterman @EdPrice-MSFT - can you take a look? (can't assign you for some reason).

**Comment by Jak-MS** [comment]
#label:"aq-pr-triaged"

**Review by EdPrice-MSFT — APPROVED** [review]
Looks good

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger9** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @SMBrook, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Review by ckittel — CHANGES_REQUESTED** [review]
@EdPrice-MSFT -- we have two other article that use this asset -- and looks like they are at the core of the content -- so they would require a bit a re-write if that's true :( :   **I suggest running this through Content Strategy for resourcing.**

 - https://github.com/MicrosoftDocs/architecture-center-pr/blob/main/docs/industries/finance/financial-risk-model.md
 - https://github.com/MicrosoftDocs/architecture-center-pr/blob/main/docs/reference-architectures/ai/batch-scoring-R-models-content.md

**Review by EdPrice-MSFT — APPROVED** [review]
Great. Thanks!

**Comment by PRMerger12** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @SMBrook, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by jborsecnik** [comment]
@ckittel. Ok to merge now? I believe you have to approve in your review for us to merge. Thanks.

**Review by ckittel — APPROVED** [review]
None of the feedback is addressed in this PR, but I don't want to block it as there is nothing wrong with this PR specifically.  @SvenAelterman -- any chance to get the delete also done [identified in the comment above](https://github.com/MicrosoftDocs/architecture-center/pull/3385#pullrequestreview-940107388) on the other page in another PR? Thanks!

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

Ready to merge. Thanks!

**Comment by PRMerger16** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @SMBrook, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
