### PR TITLE
test

### PR DESCRIPTION
**Pull request by ChandreshAwasthi**
Updating Predictive Insights

### CODE REVIEW

**Review by doodlemania2 — APPROVED** [review]

**Comment by ktoliver** [comment]
@ChandreshAwasthi Can you confirm that the pull request is ready to merge (in light of the PR title, "test"). Thanks. (It's otherwise ready to merge.)

**Comment by ChandreshAwasthi** [comment]
Yes, I didnt realize I had not fixed that comment before finalizing that PR, Silly me. 

All my changes are in it.

**Comment by ktoliver** [comment]
Great! Merging now. Thanks @ChandreshAwasthi

**Review by ktoliver — APPROVED** [review]

**Comment by ktoliver** [comment]
@doodlemania2 A merge conflict has developed. The GitHub UI isn't giving me the option to view and resolve the conflict. I don't see a file-based conflict in master. Do you have experience with resolving the issue in this repo?

**Comment by ktoliver** [comment]
I'll try a close/reopen, but that's probably not going to resolve it.

**Comment by ktoliver** [comment]
It looks like @ChandreshAwasthi opened another pull request that had these updates it and @EdPrice-MSFT merged it:

https://github.com/MicrosoftDocs/architecture-center/pull/2629

It looks like we should close this PR, then.

**Comment by ChandreshAwasthi** [comment]
I am also new to Git PRs, I see for some reason its showing commits from my other PR with EdPrice, however, that PR (2259) didnt include changes pertaining to Predictive Insights so we will have to merge PR 2260

**Comment by ktoliver** [comment]
@ChandreshAwasthi I understand; we can sort it out. 

Can you remove the file from this pull request the file that has already been merged? PRMerger is saying that something in this PR conflicts with or would overwrite a change that recently been made to master. 

(It might be as simple as pulling from master in your fork; I don't know.)

**Comment by ktoliver** [comment]
@doodlemania2 @ChandreshAwasthi Could you contact the Docs Support channel on Teams for help resolving the merge conflict? An alternative is to close the pull request and create a new one. Thanks!

**Review by ktoliver — APPROVED** [review]

**Comment by ktoliver** [comment]
@ChandreshAwasthi Thanks! The PR has been merged.

**Pull request merged**
