### PR TITLE
Typo "Azure file storage"→"Azure File Storage"

### PR DESCRIPTION
**Pull request by hyoshioka0128**
https://docs.microsoft.com/en-us/azure/architecture/data-science-process/team-lead-tasks
https://github.com/microsoftdocs/architecture-center/blob/main/docs/data-science-process/team-lead-tasks.md
#PingMSFTDocs

### CODE REVIEW

**Comment by Jak-MS** [comment]
@marktab - Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Jak-MS** [comment]
@hyoshioka0128 @marktab - "Azure File Storage" does NOT look to be a branded product and so should not be capitalized.

**Review by EdPrice-MSFT — APPROVED** [review]
Looks good!

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by EdPrice-MSFT** [comment]
#Hold-Off

**Comment by EdPrice-MSFT** [comment]
So the proper name is Azure Files: https://docs.microsoft.com/en-us/azure/storage/files/storage-files-introduction

**Comment by EdPrice-MSFT** [comment]
It's good, as is.

**Pull request closed without merging**
