### PR TITLE
Updates to Migration Tools

### PR DESCRIPTION
**Pull request by fbinotto**
Comparing GPC and Azure Migration Tools.
Re-formatted table headers to be consistent with rest of document.
Added relevant migration tools, links and descriptions.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@fbinotto : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@fbinotto : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by cjnova — CHANGES_REQUESTED** [review]
I made previous changes about Azure VMWare by CloudSimple as long as is a deprecated solution in favor of a Microsoft native soloution approved by VMWare. If you go to the documentation refered in the link [https://azure.microsoft.com/en-us/services/azure-vmware/#faq](https://azure.microsoft.com/en-us/services/azure-vmware/#faq) you can chek in FAQ section how our solution is different from CloudSImple. Cloudsimple was the AVS 1.0 and now we have AVS 2.0 from Microsoft. I suggest to revert changes from this PR related to a previous hand-off PR

**Comment by fbinotto** [comment]
Based on @cjnova comments, I'm closing this PR and will create a new one.

**Pull request closed without merging**
