### PR TITLE
Added component links

### PR DESCRIPTION
**Pull request by wedoazure**
Added required component links for the architecture

### CODE REVIEW

**Comment by Jak-MS** [comment]
@frankmigacz 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by frankmigacz — APPROVED** [review]
I AM APPROVING THIS CHANGE even though the fourth link of the four added links changes i18n from en-us to en-ie ☘️ which results in "Windows Admin Center" changing to "Windows Admin Centre". I AM OK WITH THIS!
#sign-off

**Comment by frankmigacz** [comment]
#sign-off

**Comment by frankmigacz** [comment]
@wedoazure you'll have to decide whether or not to change that link and then sign-off

**Comment by wedoazure** [comment]
> @wedoazure you'll have to decide whether or not to change that link and then sign-off

Link updated to standard regional setting. Good catch, my browser did it automatically!

**Review by frankmigacz — APPROVED** [review]
Consistent!

**Review by frankmigacz — APPROVED** [review]
Trying the approval again

**Review by jborsecnik — APPROVED** [review]

**Pull request merged**
