### PR TITLE
(AzureCXP) mention outgoing traffic rules

### LINKED ISSUE #1493: Ports for AD
Article mentions, "The Active Directory subnet NSG requires rules to permit incoming traffic from on-premises."  The article should be updated to mention that rules are required to permit outbound traffic to on-premises as well.  The ports need to be bi-directional, not one way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65f26361-0def-4ae9-e28a-8a8d4f97b87f
* Version Independent ID: ef55eb02-6543-88ad-4f89-5a553848bc67
* Content: [Extend your on-premises Active Directory domain to Azure - Azure Reference Architectures](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adds-extend-domain)
* Content Source: [docs/reference-architectures/identity/adds-extend-domain.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/identity/adds-extend-domain.md)
* Service: **architecture-center**
* Sub-service: **reference-architecture**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

### PR DESCRIPTION
**Pull request by PramodValavala-MSFT**
resolves #1493

### CODE REVIEW

**Comment by PRMerger17** [comment]
@PramodValavala-MSFT : Thanks for your contribution! The author, @telmosampaio, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @MikeWasson - The listed author @telmosampaio doesn't appear in the **Assignees** box. Could you review the proposed changes? Thanks.

**Comment by doodlemania2** [comment]
#sign-off

**Comment by PRMerger8** [comment]
@doodlemania2: I'm sorry - only the author of this article, @telmosampaio, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by MikeWasson** [comment]
#sign-off

**Comment by PRMerger9** [comment]
@MikeWasson: I'm sorry - only the author of this article, @telmosampaio, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
