### PR TITLE
Adapting to upcoming Portal UI changes on App Registration

### PR DESCRIPTION
**Pull request by luisgmsft**

### CODE REVIEW

**Comment by PRMerger6** [comment]
@luisgmsft : Thanks for your contribution! The author, @MikeWasson, has been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@Jak-MS : Thanks for your contribution! The author, @MikeWasson, has been notified to review your proposed change.

**Comment by doodlemania2** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@doodlemania2: I'm sorry - only the author of this article, @MikeWasson, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by MikeWasson** [comment]
#sign-off

**Pull request merged**
