### PR TITLE
Updates to App gateway and Traffic Manager article

### PR DESCRIPTION
**Pull request by sonmitt**
Updates to diagram, VNet Peering and Azure DNS documentation

### CODE REVIEW

**Comment by PRMerger8** [comment]
@sonmitt : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@EdPrice-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by EdPrice-MSFT — APPROVED** [review]
Looks great. I made a minor punctuation edit.

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Pull request merged**
