### PR TITLE
Update Landing Page

### PR DESCRIPTION
**Pull request by MarkSimos**
Tom Shinder and I co-wrote updated intro. Should also change the title to "Azure Security Compass - Architecture" as well

### CODE REVIEW

**Comment by PRMerger8** [comment]
@MarkSimos : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @MikeWasson - Could you review the pull request and indicate whether it's ready to merge? Thanks!

**Comment by MikeWasson** [comment]
@david-stanford Please review - thanks!

**Comment by david-stanford** [comment]
Closing as we completely re-wrote this page together.

**Pull request closed without merging**
