### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by LazaUK**
Added information about Azure RBAC, as currently we have only classic subscription administrator roles listed. Also removed inaccurate statement about assignment of individual permissions - we add permissions to roles and then assign the roles to end users in Azure, not individual permissions.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@LazaUK : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@EdPrice-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by EdPrice-MSFT — DISMISSED** [review]
Good change.

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger9** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @doodlemania2, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger7** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by ktoliver — APPROVED** [review]
Resolved the merge conflict that was caused by another PR merged this morning.

**Pull request merged**
