### PR TITLE
Resolve syncing conflicts from repo_sync_working_branch to master

### PR DESCRIPTION
**Pull request by openpublishbuild**
Pull request opened by Docs to resolve syncing conflicts from repo_sync_working_branch to master.

### CODE REVIEW

**Comment by MikeWasson** [comment]
@tysonn Should I resolve the conflicts or your team is working on it?

**Comment by jborsecnik** [comment]
@MikeWasson, can you resolve it? Thanks.

**Comment by MikeWasson** [comment]
@jborsecnik Sorry, I didn't see that I was tagged on this. I'll take a look

**Comment by Jak-MS** [comment]
@MikeWasson - when you have the chance, can you resolve this? thanks.

**Comment by ktoliver** [comment]
@Taojunshen Will you see whether this publishing PR needs to be merged or closed? It was opened September 30.

**Comment by Jak-MS** [comment]
@MikeWasson - nudge on this... we're not sure how to handle this as it accumulates branch conflicts. can you take a look at let us know? thanks.

**Comment by tfosmark** [comment]
The PR review team does not handle the sync PRs. We're just alerting you to the issue. Thanks!

**Comment by jborsecnik** [comment]
@MikeWasson ...

**Comment by MikeWasson** [comment]
@tfosmark  I resolved the merge conflicts, this should be OK to merge now.

**Pull request merged**
