### PR TITLE
fix: Always point to the latest KEDA docs

### PR DESCRIPTION
**Pull request by tomkerkhove**

### CODE REVIEW

**Review by ckittel — APPROVED** [review]
LGTM, thanks for the change!

**Comment by tomkerkhove** [comment]
Happy to help!

**Comment by ckittel** [comment]
#sign-off

**Comment by PRMerger14** [comment]
@ckittel: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
