### PR TITLE
Update design-governance.md

### PR DESCRIPTION
**Pull request by HelderN**
Removed reference that it was incorrect.
Tags can be inherit and using built in policies.

### CODE REVIEW

**Comment by PRMerger7** [comment]
@HelderN : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by EdPrice-MSFT** [comment]
FYI to @PageWriter-MSFT @josevarela and @david-stanford - Needs a review.

**Comment by EdPrice-MSFT** [comment]
Following up on this internally, with the team...

**Review by EdPrice-MSFT — APPROVED** [review]
Verified: https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/tag-policies

Great edit. Thanks!

**Comment by EdPrice-MSFT** [comment]
@ktoliver 

#Sign-Off

Thanks!

**Pull request merged**
