### PR TITLE
Adding some additional guidance

### PR DESCRIPTION
**Pull request by udidahan**

### CODE REVIEW

**Comment by Court72** [comment]
@EdPrice-MSFT 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by udidahan** [comment]
Hey folks, is there anything I can do to help get this unstuck? Thanks.

**Comment by Court72** [comment]
@EdPrice-MSFT  - Could you review this proposed update to your article and enter `#sign-off` in a comment if it's ready for merge?

Thanks!

**Review by EdPrice-MSFT — APPROVED** [review]
Looks great!

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Pull request merged**
