### PR TITLE
Azure Stack multitenant VPN gateway

### PR DESCRIPTION
**Pull request by njray**
Got the OK from Masashi and Mike to add these updates from Marc van Eijk. A new diagram goes with this change. Let me know if there's a different way to make this change. Thanks! -- Nanette (nanetteR@ronline.com)

### CODE REVIEW

**Comment by njray** [comment]
@MikeWasson —This PL is related to Ed Price's email to you and Mashashi from March 4. Does it look OK? Thanks!

**Comment by PRMerger6** [comment]
@njray : Thanks for your contribution! The author, @RohitSharma-pnp, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
@MikeWasson - The listed author doesn't appear in the **Assignees** box. Could you review the proposed changes? Thanks.

**Comment by MikeWasson** [comment]
superceded by MicrosoftDocs/architecture-center-pr#385

**Pull request closed without merging**
