### PR TITLE
fix Azure Load Balancer scope

### PR DESCRIPTION
**Pull request by MikeBazMSFT**

### CODE REVIEW

**Comment by PRMerger13** [comment]
@MikeBazMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
Microsoft authors of articles need to make updates through the private repository so the updates can be staged and validated by the current validation rules. After you review staging and fix all validation issues, you can add the sign-off comment to let the PR reviewers know the updates are ready to be merged.It's easy to access the private repo version of your articles in GitHub. Just add -pr to the URL, as follows: 
 Public repo URL: https://github.com/MicrosoftDocs/azure-docs 
 Private repo URL: https://github.com/MicrosoftDocs/azure-docs-pr 
 We have closed this pull request. Please resubmit the updates through the private repo. For more information, [see the contributor guide].(https://docs.microsoft.com/en-us/contribute/)

**Review by EdPrice-MSFT — APPROVED** [review]
Great change

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger17** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @MikeBazMSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger16** [comment]
@MikeBazMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@MikeBazMSFT For next time, the metadata **ms.author** value must be a Microsoft alias.

**Review by ktoliver — APPROVED** [review]

**Pull request merged**
