### PR TITLE
Added new section - Next steps

### PR DESCRIPTION
**Pull request by raunakjhawar**
Added 3 new links for readers to understand more about hybrid connectivity using Azure functions.

### CODE REVIEW

**Comment by raunakjhawar** [comment]
Hi @ktoliver, any chance to prioritize this PR?

**Comment by ktoliver** [comment]
> Hi ktoliver, any chance to prioritize this PR?

@raunakjhawar Yes. We can merge after the content team signs off/approves.

@doodlemania2 Could you take a look at the proposed update? Thanks.

**Review by doodlemania2 — APPROVED** [review]

**Comment by doodlemania2** [comment]
#sign-off

**Comment by PRMerger14** [comment]
@doodlemania2: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
