### PR TITLE
Refresh references to Azure Search

### PR DESCRIPTION
**Pull request by HeidiSteen**

### CODE REVIEW

**Comment by PRMerger17** [comment]
@HeidiSteen : Thanks for your contribution! The author(s) have been notified to review your proposed change. @zoinerTejada

**Comment by HeidiSteen** [comment]
@jelledruyts

**Comment by doodlemania2** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@doodlemania2: I'm sorry - only the author of this article, @zoinerTejada, @jelledruyts, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
