### PR TITLE
AFS update

### PR DESCRIPTION
**Pull request by DevOpsStyle**
Good morning Team,

Since Azure File Sync is the latest service that Microsoft recommends for the implementation of new file synchronisation solutions, I have added reference to this new service to the articles.

Thanks for your help

### CODE REVIEW

**Comment by Jak-MS** [comment]
@EdPrice-MSFT 
- Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by EdPrice-MSFT — APPROVED** [review]
Looks great. Made some edits.

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by DevOpsStyle** [comment]
@EdPrice-MSFT Hello Ed, Thanks a lot for your precious feedback and support. There is anything else i need to do? Because I see the error above "invalid sign-off". There is something i have to do?

Thank you

**Pull request merged**
