### PR TITLE
Added Private DNS comparison with GCP

### PR DESCRIPTION
**Pull request by infosatheesh2020**

### CODE REVIEW

**Comment by PRMerger8** [comment]
@infosatheesh2020 : Thanks for your contribution! The author(s) have been notified to review your proposed change. @fbinotto

**Comment by ktoliver** [comment]
@fbinotto could you review the proposed update? Thanks.

**Comment by ktoliver** [comment]
Hi @infosatheesh2020 - This pull request was opened in the public repository. Microsoft-internal contributors who update Azure Architecture Center articles are encouraged to create pull requests in the private repository instead. I'll move this commit to the private repo and send you information via email about working in the private repo in the future. Thank you!

**Comment by ktoliver** [comment]
The PR will be reviewed in the private repo. We'll close this PR. Thanks.

**Pull request closed without merging**
