### PR TITLE
adding Profisee MMU reference architecture document

### PR DESCRIPTION
**Pull request by brianbarnett316**
Submitting new docs to review how to use the Profisee MDS Migration Utility (MMU) to migrate from Microsoft MDS to Profisee.

### CODE REVIEW

**Comment by EdPrice-MSFT** [comment]
@brianbarnett316 

We can publish this as is on our blog: http://aka.ms/DevBlog 

For a Reference Architecture, we'd need it to follow our template: https://learn.microsoft.com/en-us/contribute/architecture-center/sample-solution-templates

Also reaching out on LinkedIn.

Thanks!

**Comment by EdPrice-MSFT** [comment]
@brianbarnett316 

Was anyone else involved in writing this? We'd also give them credit.

I think what we're missing the most is the Considerations. We should add three sub-sections, to continue what you started with your "Technical considerations" section... basically fill out a "Cost optimization" section and pick two more (these are based on our WAF pillars):

## Considerations

> REQUIRED STATEMENT: Include the following statement to introduce this section:

These considerations implement the pillars of the Azure Well-Architected Framework, which is a set of guiding tenets that can be used to improve the quality of a workload. For more information, see [Microsoft Azure Well-Architected Framework](/azure/architecture/framework).

> Are there any lessons learned from running this that would be helpful for new customers?  What went wrong when building it out?  What went right?
> How do I need to think about managing, maintaining, and monitoring this long term?

> REQUIREMENTS: 
>   You must include the "Cost optimization" section. 
>   You must include at least two of the other H3 sub-sections/pillars: Reliability, Security, Operational excellence, and Performance efficiency.

### Reliability

> REQUIRED STATEMENT: If using this section, include the following statement to introduce the section:

Reliability ensures your application can meet the commitments you make to your customers. For more information, see [Overview of the reliability pillar](/azure/architecture/framework/resiliency/overview)."

> This section includes resiliency and availability considerations. They can also be H4 headers in this section, if you think they should be separated.
> Are there any key resiliency and reliability considerations (past the typical)?

### Security

> REQUIRED STATEMENT: If using this section, include the following statement to introduce the section:

Security provides assurances against deliberate attacks and the abuse of your valuable data and systems. For more information, see [Overview of the security pillar](/azure/architecture/framework/security/overview).

> This section includes identity and data sovereignty considerations.
> Are there any security considerations (past the typical) that I should know about this?

### Cost optimization

> REQUIRED: This section is required.

> REQUIRED STATEMENT: Include the following statement to introduce the section:

Cost optimization is about looking at ways to reduce unnecessary expenses and improve operational efficiencies. For more information, see [Overview of the cost optimization pillar](/azure/architecture/framework/cost/overview).

> How much will this cost to run? See if you can answer this without dollar amounts.
> Are there ways I could save cost?
> If it scales linearly, than we should break it down by cost/unit. If it does not, why?
> What are the components that make up the cost?
> How does scale affect the cost?

> Link to the pricing calculator (https://azure.microsoft.com/pricing/calculator) with all of the components in the architecture included.
> If it makes sense, include small/medium/large configurations. Describe what needs to be changed as you move to larger sizes.

### Operational excellence

> REQUIRED STATEMENT: If using this section, include the following statement to introduce the section:

Operational excellence covers the operations processes that deploy an application and keep it running in production. For more information, see [Overview of the operational excellence pillar](/azure/architecture/framework/devops/overview).

> This includes DevOps, monitoring, and diagnostics considerations.
> How do I need to think about operating this solution?

### Performance efficiency

> REQUIRED STATEMENT: If using this section, include the following statement to introduce the section:

Performance efficiency is the ability of your workload to scale to meet the demands placed on it by users in an efficient manner. For more information, see [Performance efficiency pillar overview](/azure/architecture/framework/scalability/overview).

> This includes scalability considerations.
> Are there any key performance considerations (past the typical)?
> Are there any size considerations around this specific solution? What scale does this work at? At what point do things break or not make sense for this architecture?

**Comment by brianbarnett316** [comment]
Hello Ed,

I was not involved in writing this.  I'm merely the submitter :-).

I notified the team with your feedback and they are in the process of updating the document.

**Comment by EdPrice-MSFT** [comment]
@brianbarnett316 - Okay, thanks!

**Comment by EdPrice-MSFT** [comment]
We're moving this to a Word document process.

**Pull request closed without merging**
