### PR TITLE
Update cqrs.md

### PR DESCRIPTION
**Pull request by ferdeen**
Looks like a bullet point is missing.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@ferdeen : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MikeWasson** [comment]
#sign-off

**Comment by PRMerger9** [comment]
@MikeWasson: I'm sorry - only the author of this article, @dragon119, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by chbain** [comment]
Formatting correction verified.

**Comment by ferdeen** [comment]
Thanks all!

**Pull request merged**
