### PR TITLE
Update secure-baseline-aks.md

### PR DESCRIPTION
**Pull request by jboeshart**
Fix typo and some verbiage

### CODE REVIEW

**Comment by PRMerger18** [comment]
@jboeshart : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@jboeshart : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@jboeshart : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@jboeshart : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ckittel** [comment]
#sign-off

**Comment by PRMerger10** [comment]
@ckittel: I'm sorry - only the author of this article, @PageWriter-MSFT, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
We'll merge the PR.

@jboeshart Would you make future content revisions in the private repo?

@ckittel Thanks for your review. PRs in the public repo need sign-off by a member of the content team or a PM.

**Pull request merged**
