### PR TITLE
Clarifying VNET integration and APIM tiers

### PR DESCRIPTION
**Pull request by nzthiago**

### CODE REVIEW

**Comment by PRMerger7** [comment]
@nzthiago : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@doodlemania2 Could you review the latest commit? If I understand what's being said in line 108, "in" seems more clear than "with."  "Into"?

**Comment by doodlemania2** [comment]
yes, this looks good #sign-off

**Comment by PRMerger9** [comment]
@doodlemania2: I'm sorry - only the author of this article, @hannesne, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by nzthiago** [comment]
Thank you both. @ktoliver I went with "integrated with" because that seems the prevalent way of saying it from the Azure Functions documentation that is linked to in that 108 ("When you use VNet Integration with VNets in the same region"): https://docs.microsoft.com/en-us/azure/azure-functions/functions-networking-options#regional-virtual-network-integration

**Comment by ktoliver** [comment]
Thanks!

**Pull request merged**
