### PR TITLE
Proposing new hybrid architecture: Azure Stack HCI Stretched Cluster for disaster recovery

### PR DESCRIPTION
**Pull request by seesharprun**
Proposing a new **hybrid** reference architecture that includes an Azure Stack HCI cluster consisting of 4+ nodes and 4+ volumes stretched across two physical locations along with synchronous/asynchronous storage replication.

The architecture is not quite ready to merge:

- [x] Outline done
- [x] Rough draft done
- [x] Reviewed by engineering SMEs
- [x] Copy-edit and compliance review complete

### CODE REVIEW

**Comment by PRMerger15** [comment]
@seesharprun : Thanks for your contribution! The author(s) have been notified to review your proposed change. @githubusername

**Comment by ktoliver** [comment]
PR reviewers: Per @tfosmark, the contributor will collaborate with the content team in this PR to develop the proposed content.

**Comment by PRMerger9** [comment]
@polichtm : Thanks for your contribution! The author(s) have been notified to review your proposed change. @githubusername

**Comment by PRMerger10** [comment]
@polichtm : Thanks for your contribution! The author(s) have been notified to review your proposed change. @githubusername

**Comment by PRMerger13** [comment]
@polichtm : Thanks for your contribution! The author(s) have been notified to review your proposed change. @githubusername

**Comment by PRMerger15** [comment]
@MalihusWP : Thanks for your contribution! The author(s) have been notified to review your proposed change. @githubusername

**Comment by PRMerger6** [comment]
@emereb : Thanks for your contribution! The author(s) have been notified to review your proposed change. @githubusername

**Comment by PRMerger15** [comment]
@polichtm : Thanks for your contribution! The author(s) have been notified to review your proposed change. @githubusername

**Comment by PRMerger14** [comment]
@polichtm : Thanks for your contribution! The author(s) have been notified to review your proposed change. @githubusername

**Comment by PRMerger20** [comment]
@polichtm : Thanks for your contribution! The author(s) have been notified to review your proposed change. @githubusername

**Comment by PRMerger13** [comment]
@polichtm : Thanks for your contribution! The author(s) have been notified to review your proposed change. @githubusername

**Comment by PRMerger9** [comment]
@MalihusWP : Thanks for your contribution! The author(s) have been notified to review your proposed change. @githubusername

**Comment by PRMerger19** [comment]
@MalihusWP : Thanks for your contribution! The author(s) have been notified to review your proposed change. @githubusername

**Comment by PRMerger17** [comment]
@polichtm : Thanks for your contribution! The author(s) have been notified to review your proposed change. @githubusername

**Comment by PRMerger14** [comment]
@polichtm : Thanks for your contribution! The author(s) have been notified to review your proposed change. @githubusername

**Comment by PRMerger19** [comment]
@polichtm : Thanks for your contribution! The author(s) have been notified to review your proposed change. @githubusername

**Comment by PRMerger8** [comment]
@polichtm : Thanks for your contribution! The author(s) have been notified to review your proposed change. @githubusername

**Comment by PRMerger14** [comment]
@polichtm : Thanks for your contribution! The author(s) have been notified to review your proposed change. @githubusername

**Comment by PRMerger13** [comment]
@MalihusWP : Thanks for your contribution! The author(s) have been notified to review your proposed change. @githubusername

**Comment by PRMerger7** [comment]
@MalihusWP : Thanks for your contribution! The author(s) have been notified to review your proposed change. @githubusername

**Comment by PRMerger14** [comment]
@polichtm : Thanks for your contribution! The author(s) have been notified to review your proposed change. @githubusername

**Comment by seesharprun** [comment]
This PR is ready.

**Comment by ktoliver** [comment]
@seesharprun Thanks. The commit has been moved to the private repo for quality checks and merging. It's assigned to @doodlemania2 . We'll close this PR

**Pull request closed without merging**
