### PR TITLE
WIP: New DataOps NiFi Sentiment Analysis and Face Recognition solution idea.

### PR DESCRIPTION
**Pull request by Katie-Novotny**

### CODE REVIEW

**Comment by PRMerger14** [comment]
@Katie-Novotny : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@EdPrice-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger-2** [comment]
@EdPrice-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ShannonLeavitt** [comment]
@EdPrice-MSFT - If you accept these changes, the commits will need to be moved to the private repo for review and automated checks. Let us know if you'd like us to help with that by sending email to the PR Review team's alias.

**Comment by EdPrice-MSFT** [comment]
@ShannonLeavitt - Yes, that would be great. Done. Thanks!

**Comment by ShannonLeavitt** [comment]
@EdPrice-MSFT - I'm preparing to move the commits to the private repo now.

**Comment by ShannonLeavitt** [comment]
I'm reopening this PR so that @Katie-Novotny can add a few more commits.

**Comment by PRMerger13** [comment]
@Katie-Novotny : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@Katie-Novotny : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by EdPrice-MSFT** [comment]
@Katie-Novotny - Are we okay removing this PR? Do we have it covered the private repo?

Thanks!

**Comment by EdPrice-MSFT** [comment]
I followed up with Katie and team. This PR is no longer needed.

**Pull request closed without merging**
