### PR TITLE
Update multi-forest-azure-managed.md

### PR DESCRIPTION
**Pull request by jufuku0108**
AAD DS supports using ADMX as group policy template as states below.
https://docs.microsoft.com/en-us/azure/active-directory-domain-services/manage-group-policy

### CODE REVIEW

**Comment by PRMerger6** [comment]
@jufuku0108 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by doodlemania2** [comment]
#sign-off

**Comment by PRMerger14** [comment]
@doodlemania2: I'm sorry - only the author of this article, @nehalineogi, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Review by ktoliver — APPROVED** [review]

**Comment by ktoliver** [comment]
Merging per @doodlemania2

**Pull request merged**
