### PR TITLE
Updating Principles

### PR DESCRIPTION
**Pull request by a11smiles**
Current documentation is incorrect as it doesn't adequately reflect the core principles of the Perf Efficiency pillar. Additionally, the content presented under the listed principles is misdirected. 

I've updated the principles to reflect the WAF/Go-Live Assessments along with adding the correct supporting documentation.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@a11smiles : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ckittel** [comment]
@PageWriter-MSFT @david-stanford, just FYI in case you haven't seen it (you probably already have context on this)

**Comment by a11smiles** [comment]
@ckittel I've already pinged @david-stanford and he knows about it and the context. Just waiting for him to approve the merge.  We need this merged ASAP for our WAF documentation before we (CSU) begin our WAF Assessments. We have one coming up next week.

**Comment by ckittel** [comment]
Yeah, figured there was context external to this PR.  But thought I'd ping key players in case there wasn't.  All good, I'll slither away now :)

**Comment by PRMerger16** [comment]
@a11smiles : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by david-stanford** [comment]
This was incorporated last month through a rewrite of the section

**Pull request closed without merging**
