### PR TITLE
New: Reference architecture for Public facing ACR

### PR DESCRIPTION
**Pull request by Kumar-Ashwin-Hubert**
Reference architecture for the deployment of secured Azure Container Registry (ACR) for consuming images and artifacts by customer applications over public internet.

Before selecting the "Create pull request" button:  

1. Enter a meaningful title above^, using a prefix if necessary and keywords "New" or "Update" indicating the nature of changes.

2. Describe the summary, scope, and intent of this PR:  
Reference architecture for the deployment of secured Azure Container Registry (ACR) for consuming images and artifacts by customer applications over public internet.

3. Insert links(s) to any related work item(s) or supporting detail:  

  

  
<details><summary>AFTER YOUR PR HAS BEEN CREATED, expand this section for tips and additional instructions.</summary>    
      

These are common guidelines for contributions across the repos managed by the Cloud Architecture Content Team (CACT). Some repositories may have additional specific requirements that are not listed here.   

## Guidance for all contributors  
  
  | **Topic** | **Guidance** |
  | ----------| ------------ |
  | **Draft PR** | If your PR will be a work-in-progress for more than a day or two, select the **Convert to draft** link in the upper right of the page (under **Reviewers**) to change it to a draft. For future reference, you can also do this using the **Create pull request** button drop-down during PR creation. | 
  | **ms.date metadata** | <ul><li>Don't update an article's "ms.date" metadata property unless you've done a **full freshness review** of the content. A full freshness review includes changes required to correct or improve the **full** technical accuracy of the article.</li><li>Don't update "ms.date" if you're doing targeted changes to improve non-technical aspects of the article, such as editorial quality, art improvements, article template alignment, etc.</li><li>If you've changed any "ms.date" properties for work that wasn't part of full review for freshness, please reset them to their previous value.</li></ul> | 
  | **Placement and linking** | If you're creating a new article or articles, include updates to the related TOC.yml file to propose where the article(s) should be placed. Also consider other places within the document set where it would be beneficial to cross-reference and link to your new article(s). | 
  | **PR build** | After you open your PR, and for each successive commit that you push to your branch, the publishing platform will run validation on the files in your pull request. A summary of the build results for each file will be inserted inline into your pull request, which includes any build suggestions/warnings/errors. PRs cannot be merged until all build errors and most warnings are resolved. |
  | **Publishing** | Following a successful merge, most repos publish to the live site at least once per (business) day, usually around 10am Pacific. |
  | **Additional resources** | <ul><li>[Learn.Microsoft.Com contributor guide](https://review.learn.microsoft.com/help/contribute/?branch=main)</li></ul>
  
## Additional guidance for private repos and internal contributors  

  | **Topic** | **Guidance** | 
  | ----------| ------------ | 
  | **PR size** | If your PR is more than ~5 lines of changes, or you'd like for the changes to go through editorial or larger review, open a contribution request at https://aka.ms/Contribution and include a link to the PR in response #8. Once it's processed, you'll be notified of the next steps.  |
  | **PR title prefix** | Select the **Edit** button to the right of the PR title if you need to revise it. The following prefixes are reserved for specific contribution types:<br/><br/><ul><li>**[Quality Check]** - maintenance work related to content quality (edit passes, art improvements, template alignment)</li><li>**[LinkFix]** - recurring/adhoc PRs to correct link URLs</li><li>**[Pipeline]** - new/updated contributor success pipeline content</li><li>**[WIP]** - a work-in-progress draft requiring several days/weeks</li></ul> |
  | **PR preview** | Following successful build of your PR, publishable files will also include **Preview URL** links to staged previews of your new/updated articles. Be sure to review these for verification of your intended contributions, or to send to other internal contributors for review. |
  | **PR sign-off (public repo)** | If an article you own is updated in a public repo PR, you are responsible for sign-off. You will be automatically notified via email. The PR will not be merged until you've had a chance to review and sign-off. |
  | **PR sign-off (private repo)** | After you've completed your proposed changes, addressed build warnings, and completed all review work, you can begin the sign-off process for review and merge:<br/><br/><ol><li>If your PR is in draft mode, remove "[WIP]" from the title and select **Ready for review** button at the bottom of the PR.</li><li>Enter "#sign-off" in a new comment. This comment indicates that **you're confident the work meets or exceeds Microsoft's standards for publication**, and will trigger the review process.</li><li>Your PR may be selected for initial review by the CACT. Following CACT review, you may receive questions or requests for additional changes. You should have initial feedback from CACT review within a few business days. If you have an urgent request or need to contact the team, please mention `@MicrosoftDocs/cloud-architecture-content-team-pr-reviewers` in your PR and someone will get back to you. After CACT review is complete, a `CACT #sign-off` will be added.</li><li>Final review/merge is done by the PR review team. The PR team may also respond with feedback, categorized as "Blocking" (requires action from you), or "Non-blocking" (to be addressed in a future PR).</li></ol> |
  | **Additional resources** | <ul><li>[Learn.Microsoft.Com internal contributor guide](https://review.learn.microsoft.com/help/contribute/?branch=main)</li><li>Authoring templates: [architecture-center-pr](https://review.learn.microsoft.com/help/contribute/architecture-center/templates/sample-solution-templates?branch=main), [well-architected-pr](https://review.learn.microsoft.com/help/contribute/global-waf-template?branch=main)</li><li>To contact the CACT use [e-mail](mailto:cact-pr-reviewers@microsoft.com?subject=Help%20with%20pull%20request), or @mention our GitHub team in your PR comments using: `@MicrosoftDocs/cloud-architecture-content-team-pr-reviewers`</li></ul>
</details>

### CODE REVIEW

**Comment by Kumar-Ashwin-Hubert** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Comment by Court72** [comment]
@MicrosoftDocs/cloud-architecture-content-team-pr-reviewers - Please review the proposed changes. If you want to move forward with the content, note that the commits will need to be moved into the private repo for staging and review.
		
#label:"aq-pr-triaged"
#label:"pending-content-team/business-approval"
Cc: @MicrosoftDocs/public-repo-pr-review-team

**Comment by BryanLa** [comment]
#label:"cact-review-in-progress"

**Comment by BryanLa** [comment]
Hi @Kumar-Ashwin-Hubert - thank very much for your contribution. 

It appears that you are a Microsoft employee, but please let me know if I'm mistaken. If you are an employee, I can provide alternate instructions for your submission of this content..

**Comment by Kumar-Ashwin-Hubert** [comment]
Hi @BryanLa - Yes I am a Microsoft employee.

**Comment by rajesh-ms** [comment]
> Hi @Kumar-Ashwin-Hubert - thank very much for your contribution.
> 
> It appears that you are a Microsoft employee, but please let me know if I'm mistaken. If you are an employee, I can provide alternate instructions for your submission of this content..

Hi Bryan, Providing you little background, I'm coauthor for this architecture and MS employee as well. The similar architecture was implemented for a customer, and we derived a reference architecture out of that work all executed by MS.

**Comment by BryanLa** [comment]
@rajesh-ms - thanks for your follow up. This looks like a great candidate for submission and we really appreciate all of the work you've both done on this.

@Kumar-Ashwin-Hubert - per our Teams chat, unfortunately, we cannot accept contributions of this magnitude without going through our contribution pipeline process, which provides proper technical and editorial review. This will also require your pull request to be opened in our private repo (architecture-center-pr), as @Court72 mentioned previously. Your PR will also have the benefit of flowing through our build process, which provides syntax verification, grammar/spell checking, and a preview version of your content in our staging environment.

To move ahead with this, please open a PR from your fork's branch to our private repo's 'main' branch. When completed, open a request in https://aka.ms/contributions, check "Azure Architecture Center" for question # 5, and paste your PR URL in question # 7. You'll also need to either join your `Kumar-Ashwin-Hubert` GitHub account to your Microsoft corpnet account, or create a new one for employee contribution purposes. If you need help on any of this please see [Create and configure a GitHub account](https://review.learn.microsoft.com/help/get-started/setup-github?branch=main)

Please let me know if you have questions on any of this, or need assistance accessing the private repo and creating a new PR.

#please-close

**Comment by rajesh-ms** [comment]
@BryanLa @Kumar-Ashwin-Hubert - Submitted the PR request for your review and publication at https://aka.ms/contributions.

**Comment by BryanLa** [comment]
Great, thanks @rajesh-ms. Our contribution pipeline team that manages intake will be reviewing your proposal and working with others to determine the plan/timing. Keep an eye on your User Story for updates, as they will be contacting you through AzDO.

**Comment by rajesh-ms** [comment]
@BryanLa - I never received any AzDO notification, is this still in queue of contribution pipeline?
@Kumar-Ashwin-Hubert - Did you receive any AzDO notification ?

**Pull request closed without merging**
