### PR TITLE
Update population-health-management-for-healthcare.md

### PR DESCRIPTION
**Pull request by BMichaelJ**
Diagram is above and not below

### CODE REVIEW

**Comment by PRMerger16** [comment]
@BMichaelJ : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Thanks for this fix @BMichaelJ

**Pull request merged**
