### PR TITLE
Update azure-nifi-content.md

### PR DESCRIPTION
**Pull request by neeagl**
Alternative added as Airflow

### CODE REVIEW

**Comment by Jak-MS** [comment]
@MuazmaZ 
- Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by EdPrice-MSFT — APPROVED** [review]
Looks great. Thanks!

**Review by EdPrice-MSFT — APPROVED** [review]
Looks good!

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by neeagl** [comment]
Just a quick question (newbie!), how long does it take for something to go live after the merge with the main branch?

**Comment by Jak-MS** [comment]
@neeagl - varies, but if these aren't live yet, they should be published today

**Comment by neeagl** [comment]
Thanks a lot for it, this was my first time.

**Pull request merged**
