### PR TITLE
Cross-linking

### PR DESCRIPTION
**Pull request by udidahan**

### CODE REVIEW

**Comment by Court72** [comment]
@msimecek, @MicrosoftDocs/pnpftes  

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by ckittel — APPROVED** [review]
LGTM

**Comment by ckittel** [comment]
#sign-off

**Comment by Jak-MS** [comment]
@ckittel - 
PRMerger will only accept sign off from the listed 'author'. However, if you are a Microsoft employee authorized to update this content, you can send a request to [techdocprs@microsoft.com](mailto:techdocprs@microsoft.com) for this PR to be merged.  Include your role, and an explanation of why the PR should be merged without approval from the listed author.

**Review by EdPrice-MSFT — APPROVED** [review]
Looks good

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Pull request merged**
