### PR TITLE
Update load-balancing-overview.md

### PR DESCRIPTION
**Pull request by doodlemania2**

### CODE REVIEW

**Comment by PRMerger8** [comment]
@doodlemania2 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by doodlemania2** [comment]
Closes #1891

**Comment by david-stanford** [comment]
#sign-off

**Comment by PRMerger8** [comment]
@david-stanford: I'm sorry - only the author of this article, @sharad4u, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
