### PR TITLE
Update messaging.md

### PR DESCRIPTION
**Pull request by splitfinity**
Made some changes on the AWS product descriptions to more accurately describe the offerings.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@splitfinity : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
Microsoft authors of articles need to make updates through the private repository so the updates can be staged and validated by the current validation rules. After you review staging and fix all validation issues, you can add the sign-off comment to let the PR reviewers know the updates are ready to be merged.It's easy to access the private repo version of your articles in GitHub. Just add -pr to the URL, as follows: 
 Public repo URL: https://github.com/MicrosoftDocs/azure-docs 
 Private repo URL: https://github.com/MicrosoftDocs/azure-docs-pr 
 We have closed this pull request. Please resubmit the updates through the private repo. For more information, [see the contributor guide].(https://docs.microsoft.com/en-us/contribute/)

**Review by EdPrice-MSFT — APPROVED** [review]
Great updates!

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger16** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @splitfinity, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Review by EdPrice-MSFT — APPROVED** [review]
Good updates

**Comment by PRMerger12** [comment]
@EdPrice-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by EdPrice-MSFT — APPROVED** [review]
Updates look good

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger17** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @bgener, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
