### PR TITLE
DRAFT - Update teacher-provisioned-virtual-labs-azure-content.md

### PR DESCRIPTION
**Pull request by pielgarriga2**
Update body text to reflect Lab Services "Lab Plan" and update links to target current Lab Plan version docs.

### CODE REVIEW

**Comment by Jak-MS** [comment]
@EdPrice-MSFT 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by ckittel — APPROVED** [review]
LGTM

**Comment by ckittel** [comment]
I see this is still in draft @pielgarriga2 - when will this be ready for review?

**Comment by ckittel** [comment]
@pielgarriga2 between the fact that this is still in DRAFT and CLA hasn't been signed, we cannot move forward.  Should we just close?  Please let us know your intent.

**Comment by ckittel** [comment]
Been idle, so going to request that this be closed.

#please-close

**Pull request closed without merging**
