### PR TITLE
Update databases.md

### PR DESCRIPTION
**Pull request by LazaUK**
Existing documentation doesn't cover "serverless" database offerings. Add new line in the table, that compares AWS Aurora Serverless with Azure SQL Serverless and Serveless SQL Pool in Azure Synapse Analytics

### CODE REVIEW

**Comment by PRMerger8** [comment]
@LazaUK : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by EdPrice-MSFT — APPROVED** [review]
Valuable changes

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger13** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @LazaUK, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
@EdPrice-MSFT The metadata shouldn't be changed to a GitHub account that isn't linked to Microsoft and which is not in the MicrosoftDocs org (green badge). **Can I change it to you instead?** It's best to change metadata in the private repo, and contributors who open PRs in the public repo shouldn't change metadata.

**Comment by PRMerger9** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
I changed the author metadata to @EdPrice-MSFT. To change article ownership, please create a pull request in the private repo. I'll merge this now.

**Review by ktoliver — APPROVED** [review]

**Comment by ktoliver** [comment]
Thanks!

**Pull request merged**
