### PR TITLE
Updated Big Data and Analytics and added ADB

### PR DESCRIPTION
**Pull request by murariramuka**
Added Azure Databrick

### CODE REVIEW

**Comment by PRMerger10** [comment]
@murariramuka : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@EdPrice-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by EdPrice-MSFT — APPROVED** [review]
Change looks great!

**Comment by PRMerger16** [comment]
@EdPrice-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by EdPrice-MSFT — APPROVED** [review]
Change looks great!

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger10** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @doodlemania2, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
