### PR TITLE
Typo "Azure blob"→"Azure Blob"

### PR DESCRIPTION
**Pull request by hyoshioka0128**
https://docs.microsoft.com/en-us/azure/architecture/data-science-process/data-blob 
https://github.com/microsoftdocs/architecture-center/blob/main/docs/data-science-process/data-blob.md 
#PingMSFTDocs

### CODE REVIEW

**Review by EdPrice-MSFT — APPROVED** [review]
Good updates. Thanks!

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by jborsecnik** [comment]
@marktab, 

Can you review the proposed changes? According to the style guide, the name should be "Azure Blob Storage" (on first use), and "Blob Storage" subsequently.

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by marktab** [comment]
@jborsecnik I'm not confident on how to make these changes -- so here is what I did

https://github.com/hyoshioka0128/architecture-center/pull/1

**Review by EdPrice-MSFT — APPROVED** [review]
Implemented Mark's updates.

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by marktab** [comment]
#sign-off

**Pull request merged**
