### PR TITLE
Remove reference to DTL

### PR DESCRIPTION
**Pull request by francedot**
Maybe a leftover from IaaS? Not sure DevTest Labs fits in the PaaS scenario. Developers can directly use GitHub Codespaces pre-configured development environments.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@francedot : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by ckittel — APPROVED** [review]

**Comment by ckittel** [comment]
#sign-off

**Comment by PRMerger18** [comment]
@ckittel: I'm sorry - only the author of this article, @doodlemania2, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by doodlemania2** [comment]
#hold-off as this will need to be reviewed by the marketing types

**Comment by doodlemania2** [comment]
#sign-off as it's not in the diagram. thanks for the catch!

**Pull request merged**
