### PR TITLE
Add additional consideration around how much data to put in an event

### PR DESCRIPTION
**Pull request by udidahan**

### CODE REVIEW

**Comment by PRMerger9** [comment]
@udidahan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@doodlemania2 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by doodlemania2** [comment]
#sign-off

**Review by ktoliver — APPROVED** [review]

**Comment by udidahan** [comment]
Has there been a change of policy with regards to linking to related material on other sites?

I have had previous PRs accepted when there were links - for example:
https://github.com/MicrosoftDocs/architecture-center/pull/1864

**Comment by udidahan** [comment]
Hey folks, could I get a response to my question ☝️ 
cc @doodlemania2

**Comment by ktoliver** [comment]
Hi @udidahan - You're asking why @doodlemania2 removed the sentence in your pull request that contained a link to a blog post, is that right?

**Comment by udidahan** [comment]
That is correct @ktoliver

**Comment by doodlemania2** [comment]
Apologies @udidahan - no policy change, we generally don't do links off to blogs as we can't control their lifecycle. Interesting that the one from 2019 was approved. That said, let me discuss with my leadership team and we may be able to bring that back in.

**Comment by udidahan** [comment]
Thanks @doodlemania2, much appreciated.

**Comment by doodlemania2** [comment]
@udidahan - at this time, we do believe we've taken the appropriate action here regarding blog links based on our internal guidance. That it was allowed previously was in error, but we're not going to remove that link. If you are interested in contributing directly to the AAC as a partner of Azure, we'd be delighted to work with you on that. Please reach out to me via email at dermar (at) microsoft.com to discuss if you'd like!

**Comment by udidahan** [comment]
email sent 👍

**Comment by udidahan** [comment]
@doodlemania2 did you get my email? I haven't heard anything back yet.

**Comment by doodlemania2** [comment]
Well drat - I did not get it. Sorry about that - could you try again please? Confirmed that I didn't type my address wrong: dermar (at) microsoft.com

**Comment by udidahan** [comment]
Sent again. Thanks.

**Pull request merged**
