### PR TITLE
Remove reference to SQL server

### PR DESCRIPTION
**Pull request by leslie-smpx**
I did not simply replace SQL server with Cassandra DB because the architecture diagram seems to suggest that a load balancer is not needed between the business tier and the data tier

### CODE REVIEW

**Comment by PRMerger15** [comment]
@leslie-smpx : Thanks for your contribution! The author(s) have been notified to review your proposed change. @MikeWasson

**Comment by sakthi-vetrivel** [comment]
I don't think I'm the right person to review this @ktoliver

**Comment by ktoliver** [comment]
@sakthi-vetrivel Sorry, I apparently was in the wrong browser window. Apologies.

@doodlemania2 Could you review this PR? Thank you.

**Comment by ktoliver** [comment]
@doodlemania2 Is it accurate to assign PRs to you where `@MikeWasson` appears in the article metadata?

**Comment by doodlemania2** [comment]
@ktoliver - yes, I can be your reviewer!

**Pull request merged**
