### PR TITLE
Fixing typos

### PR DESCRIPTION
**Pull request by thomassantosh**
Typos in doc

### CODE REVIEW

**Comment by PRMerger18** [comment]
@thomassantosh : Thanks for your contribution! The author, @adamboeglin, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@jborsecnik : Thanks for your contribution! The author, @adamboeglin, has been notified to review your proposed change.

**Comment by jborsecnik** [comment]
@adamboeglin, the relative URL doesn't work for me. Should it instead be:  https://azure.microsoft.com/services/signalr-service/? Thanks.

**Comment by PRMerger7** [comment]
@adamboeglin : Thanks for your contribution! The author, @adamboeglin, has been notified to review your proposed change.

**Comment by adamboeglin** [comment]
> 
> 
> @adamboeglin, the relative URL doesn't work for me. Should it instead be: https://azure.microsoft.com/services/signalr-service/? Thanks.

It should be linking to: https://docs.microsoft.com/azure/azure-signalr/signalr-overview

**Comment by adamboeglin** [comment]
#sign-off

**Comment by PRMerger14** [comment]
@Jak-MS : Thanks for your contribution! The author, @adamboeglin, has been notified to review your proposed change.

**Pull request merged**
