### PR TITLE
End User Computing Services Comparison

### PR DESCRIPTION
**Pull request by sethiramicrosoft**
Added End User Computing Services section
Added EUC Services in AWS and Azure

### CODE REVIEW

**Comment by PRMerger19** [comment]
@sethiramicrosoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@EdPrice-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by EdPrice-MSFT — APPROVED** [review]
Great updates!

**Comment by PRMerger9** [comment]
@EdPrice-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by EdPrice-MSFT — DISMISSED** [review]
Approved Update! I made some minor edits.

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger9** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @BrianQu, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger12** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by ktoliver — APPROVED** [review]

**Pull request merged**
