### PR TITLE
fix invalid link to StackExchange.Redis docs

### PR DESCRIPTION
**Pull request by Ne4to**
the path is case sensitive

### CODE REVIEW

**Comment by PRMerger13** [comment]
@Ne4to : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by MikeWasson** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@MikeWasson: I'm sorry - only the author of this article, @dragon119, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by MikeWasson** [comment]
I'm the content manager for this content. OK to merge.

**Pull request merged**
