### PR TITLE
Created new FE project to browse & search icons

### PR DESCRIPTION
**Pull request by marcomws**

### CODE REVIEW

**Comment by Jak-MS** [comment]
@EdPrice-MSFT 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by EdPrice-MSFT** [comment]
This is an interesting solution. I don't think we'd be able to take this, but we'll look into it.

@ckittel, @josevarela, and @jocontr - Could we get a review of this change and the repo?

Thanks!

**Comment by ckittel** [comment]
@jocontr & @dominicallen -- This is an open source project run by this non-MSFT contributor, we wouldn't really link off to a personal repo like this (not in our current governance model), like we don't generally link to personal blogs.  I don't think reviewing the code right now is the most important part.  I think the idea is great @marcomws, but I'm not sure Microsoft's product documentation is the right place to link something like this. If you can build a project plan (maintenance, ownership, goverance) model with Content Strategy, then we can bring something like this through our content planning process.  Otherwise, we cannot just accept as is.

Before starting this project, @marcomws, did you by chance reach out to anyone on this team to talk about the game plan here?

**Comment by marcomws** [comment]
Hi @ckittel,
Thanks for your appreciation to the solution.
Actually it's my first contribution to Microsoft Docs, so I didn't know to whom I could reach out.
I can either build a project plan, just need to know if there any guide or best practice I have to follow or I can just transfer the ownership of the repo to Microsoft and continue to contribute and enrich the code as a contributor.

**Comment by EdPrice-MSFT** [comment]
@ckittel - What about publishing this on http://aka.ms/DevBlog? 

That's for more community-based efforts.

@marcomws - If this gets approved, would you be up for writing a blog post on this project?

Thanks!

**Comment by marcomws** [comment]
> @ckittel - What about publishing this on http://aka.ms/DevBlog?
> 
> That's for more community-based efforts.
> 
> @marcomws - If this gets approved, would you be up for writing a blog post on this project?
> 
> Thanks!

@EdPrice-MSFT absolutely, sure!

**Comment by marcomws** [comment]
> @marcomws - thank you for this proposal. It's an interesting idea. We have a page today that we use to make icons available to whoever needs them (https://learn.microsoft.com/en-us/azure/architecture/icons/) I'm interested in hearing what functions this page doesn't have, and the need you identified in creating your proposal? There may be opportunities for us to learn from this and add features to the existing page.

@dominicallen Thank you for your question, in a past project I had to make an architecture design to propose a solution for a client using Azure DevOps Pipelines, I spent too much time browsing for the icons (AZ DEVOPS pipelines, repos, etc) to find out that they doesn't exist in that link you mentioned. So I thought it might be helpful to browse the icons as I'm proposing with my solution.
It could be much more powerful, I can add a BE layer, call some REST API to get updated icons, I could re-write the FE solution with react or just vanilla js.

**Comment by ckittel** [comment]
I'm going to close this PR as we likely won't be accepting as-is, as it's out of our charter unfrotunately.  However, @marcomws, I request that you continue to work with @dominicallen and @EdPrice-MSFT to see if there are opportunities to contribute to our learners. We're currently refreshing how icons are handled, maybe once that is live you can blog about your explorer solution and also link to the updated icon packs.

#please-close

**Comment by dominicallen** [comment]
@marcomws thank you for the feedback regarding search functionality, I will take this back to the team to review and potentially add to the backlog for future work.

**Pull request closed without merging**
