### PR TITLE
Updating with Next Steps

### PR DESCRIPTION
**Pull request by pvmraghunandan**

### CODE REVIEW

**Comment by ktoliver** [comment]
@doodlemania2 - Are you still reviewing pull requests in the public repo? 

@pvmraghunandan - The _Next steps_ section should be a short list of links to additional content that the reader might find helpful. Detailed procedures will need to be moved to earlier in the article. Thanks!

**Comment by doodlemania2** [comment]
@ktoliver - trying to get to most of them - am i missing one?

**Comment by ktoliver** [comment]
> @ktoliver Kristine Toliver (Aquent LLC) Vendor - trying to get to most of them - am i missing one?

This one here. :) It's new. PRMerger didn't assign an author, so I'm checking to make sure that assigning it to you is still good. Thanks.

**Comment by pvmraghunandan** [comment]
@ktoliver May be renaming as "See also" makes sense? This article is very very high level & these links helps readers alot.

**Comment by ktoliver** [comment]
> May be renaming as "See also" makes sense? This article is very very high level & these links helps readers alot.

@doodlemania2 When you review this PR, could provide guidance? Thank you.

**Comment by doodlemania2** [comment]
Yes, let's please rename it to See Also.

**Comment by ktoliver** [comment]
> Yes, let's please rename it to See Also.

I'll make this change and add a few edits.

**Comment by ktoliver** [comment]
@doodlemania2 Could you take another look when you have a chance? Thanks.

**Review by doodlemania2 — APPROVED** [review]

**Comment by ktoliver** [comment]
Thanks, all.

**Comment by pvmraghunandan** [comment]
Thanks all

**Pull request merged**
