### PR TITLE
Update services.md

### PR DESCRIPTION
**Pull request by cjnova**
Renamed and fixed mapping from Compute Engine Autoscaler to Azure Virtual Machine Scale Sets.
Added Cloud GPUs mapped to GPU Optimized VMs
Changed VMWare Google service description to avoid merge conflicts with PR#2980

### CODE REVIEW

**Comment by PRMerger13** [comment]
@cjnova : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
Microsoft authors of articles need to make updates through the private repository so the updates can be staged and validated by the current validation rules. After you review staging and fix all validation issues, you can add the sign-off comment to let the PR reviewers know the updates are ready to be merged.It's easy to access the private repo version of your articles in GitHub. Just add -pr to the URL, as follows: 
 Public repo URL: https://github.com/MicrosoftDocs/azure-docs 
 Private repo URL: https://github.com/MicrosoftDocs/azure-docs-pr 
 We have closed this pull request. Please resubmit the updates through the private repo. For more information, [see the contributor guide].(https://docs.microsoft.com/en-us/contribute/)

**Review by EdPrice-MSFT — APPROVED** [review]
Good updates

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger10** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @cjnova, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
The PR review team will move these commits to the private repo for merge. We'll post here when finished.

@cjnova This PR was opened in the public repo. Would you make future updates in the private repository? I'll send email that has the details. Thanks.

**Comment by ktoliver** [comment]
@cjnova @EdPrice-MSFT This article was recently updated in master and there are 8 merge conflicts. Rather than trying to mesh the two very similar versions, it would be simpler to close this PR and open a new one in the private repo against the current version of master. You can see the merge conflicts here: https://github.com/MicrosoftDocs/architecture-center/pull/2986/conflicts

Here's what's in master: https://github.com/MicrosoftDocs/architecture-center-pr/blob/master/docs/gcp-professional/services.md

Master has been updated a few times since the 8/2/21 updates that you see in the merge conflict pane: https://github.com/MicrosoftDocs/architecture-center-pr/commits/master/docs/gcp-professional/services.md

**Comment by EdPrice-MSFT** [comment]
Moving to this new PR: https://github.com/MicrosoftDocs/architecture-center-pr/pull/3414

**Pull request closed without merging**
