### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by mark-szabo**

### CODE REVIEW

**Comment by PRMerger17** [comment]
@mark-szabo : Thanks for your contribution! The author(s) have been notified to review your proposed change. @zoinerTejada

**Comment by MikeWasson** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@MikeWasson: I'm sorry - only the author of this article, @zoinerTejada, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by chbain** [comment]
Verified typo fix.

**Pull request merged**
