### PR TITLE
Update realtime-scoring-r.md

### PR DESCRIPTION
**Pull request by Hong-Revo**
This updates the architecture to use Plumber and Traefik, rather than MMLS.

- cost considerations (MMLS is per-core licensed)
- difficulty in updating image to MMLS 9.4.7

@jreynolds01

### CODE REVIEW

**Comment by PRMerger17** [comment]
@Hong-Revo : Thanks for your contribution! The author(s) have been notified to review your proposed change. @njray

**Comment by ktoliver** [comment]
Hi @MikeWasson - The author @njray appears to be external to Microsoft. We'll assign the PR to you. Can you follow up to make sure it's reviewed? Thanks.

**Comment by PRMerger16** [comment]
@MikeWasson : Thanks for your contribution! The author(s) have been notified to review your proposed change. @njray

**Comment by MikeWasson** [comment]
@njray Is there an updated diagram?

**Comment by MikeWasson** [comment]
Moving this PR to MicrosoftDocs/architecture-center-pr#789 so that I can see it staged before publishing

**Pull request closed without merging**
