### PR TITLE
Update link to match name change on Fowler's blog.

### PR DESCRIPTION
**Pull request by pottereric**
According to Fowler's blog, he updated the title of the post from Strangler Application to Stranger Fig Application in April of 2019. This change matches the change he made.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@pottereric : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Review by EdPrice-MSFT — APPROVED** [review]
Great update!

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Pull request merged**
