### PR TITLE
Adjusted wording for better readability.

### PR DESCRIPTION
**Pull request by lukemurraynz**
Adjusted wording for better readability. #ATCP

### CODE REVIEW

**Comment by PRMerger15** [comment]
@lukemurraynz : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@EdPrice-MSFT - Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by EdPrice-MSFT — APPROVED** [review]
Looks great. Thanks!

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Pull request merged**
