### PR TITLE
Describe 'Critical Time' as an attribute useful for auto-scaling decisions

### PR DESCRIPTION
**Pull request by udidahan**

### CODE REVIEW

**Review by EdPrice-MSFT — APPROVED** [review]
Looks good!

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

"architectures" is a valid alias.

**Comment by udidahan** [comment]
Wow! This was quick!
Thanks everyone :)

**Comment by udidahan** [comment]
Hey folks, I was looking at [this doc about monitoring](https://learn.microsoft.com/en-us/azure/architecture/reference-architectures/containers/aks-mission-critical/mission-critical-data-platform#monitoring), and I think the content here may be better if it is moved there and linked to from this location. What do you think?

**Pull request merged**
