### PR TITLE
update deprecated 'group deployment' to 'deployment group'

### PR DESCRIPTION
**Pull request by zkatsavelis**

### CODE REVIEW

**Comment by PRMerger8** [comment]
@zkatsavelis : Thanks for your contribution! The author(s) have been notified to review your proposed change. @PeterTaylor9999

**Comment by ktoliver** [comment]
Hi @doodlemania2 - Could you review this pull request? Thanks.

**Comment by doodlemania2** [comment]
@ktoliver same #sign-off

**Comment by PRMerger20** [comment]
@doodlemania2: I'm sorry - only the author of this article, @PeterTaylor9999, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
