### PR TITLE
updating routing logic for azure spring apps

### PR DESCRIPTION
**Pull request by seanli1988**
At Microsoft Build this year we announced a product name change and Azure Spring Cloud is now Azure Spring Apps. The name change reflects new product capabilities and positioning for all types of Spring apps. In contrast, Azure Spring Apps was considered a niche product only for microservices when we first started. As such I would like to propose a change in the decision tree and route all types of Spring apps to Azure Spring Apps.

### CODE REVIEW

**Comment by Jak-MS** [comment]
@EdPrice-MSFT 
- Can you review this PR?
- Note that we can't merge this as is because it references an image that is not hosted in the repo. To make this change, the image file would need to be uploaded into the appropriate folder in the repo first.

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by EdPrice-MSFT** [comment]
@seanli1988 @Jak-MS @alexhart11 

I created a new private PR for this one (to get the image replaced): https://github.com/MicrosoftDocs/architecture-center-pr/pull/7848

**Comment by phehr2** [comment]
@seanli1988/@Jak-MS , the new flow indicates that Azure Container Instances, Azure Service Fabric, ARO, Azure Container Apps, and AKS should only be used for lift and shift migrations; which is a significant change from the previous version of the decision tree. This PR indicates that it was intended for making changes to Azure Spring Apps. Were other areas of the flow inadvertently updated, or is this truly the new direction?

**Comment by seanli1988** [comment]
before I do the imagine editing properly, would this work?
decision tree

**Comment by phehr2** [comment]
Yes, that down arrow is what I noticed was missing. I also noticed that Azure App Service was moved down in the tree but it makes more sense where it is now, below Spring Apps and Functions, which are more specialized.  Wouldn't hurt to rename "full-fleged" to "full-fledged" as well, while you're in there :) Thank you!

**Comment by seanli1988** [comment]
Decision tree (1)

**Comment by phehr2** [comment]
Looks great.

**Comment by seanli1988** [comment]
@phehr2 can you take that image and update the page or do you need me to do another pr? last time i created a pr i did it wrong and ed had to redo it. :(

**Comment by phehr2** [comment]
@seanli1988, I'm sorry but I'm not a contributor for this project. I just happened to notice that the decision tree which I reference often had changed, prompting me to track down the PR that changed it. Would you rather have me open a new Issue and attach your updated diagram to see if we can get someone else to take it?

**Comment by seanli1988** [comment]
@EdPrice-MSFT I tried but don't have permissions to add images to the image folder. Can you merge this change?
image

**Pull request closed without merging**
