### PR TITLE
Remove duplicate entry in regards to SQL Instance

### PR DESCRIPTION
**Pull request by SMBrook**
Removing duplicate text in regards to SQL Instance optimization, already exists on point 3 in Hybrid cost list.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@SMBrook : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by EdPrice-MSFT — APPROVED** [review]
Good change.

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger17** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @v-aangie, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
