### PR TITLE
NDVALPHA-UPDATED-FSLOGIX-PROFILEMGMT-AND-ADCONNECT

### PR DESCRIPTION
**Pull request by NDVALPHA**
NDVALPHA-UPDATED-FSLOGIX-PROFILEMGMT-AND-ADCONNECT.
Everything is ready.
Thank you.

### CODE REVIEW

**Comment by ShannonLeavitt** [comment]
Hi @EdPrice-MSFT - Can you review the proposed changes? IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

Note that lines 202-203 need to be indented 3 spaces, and the link needs to be made relative.

#label:"aq-pr-triaged"
#assign:@MicrosoftDocs/public-repo-pr-review-team

**Review by EdPrice-MSFT — APPROVED** [review]
Looks great!

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger14** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
