### PR TITLE
Updated Migration Tools section

### PR DESCRIPTION
**Pull request by fbinotto**
Re-formatted table headers to be consistent with rest of document. Added relevant migration tools, links and descriptions.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@fbinotto : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
Microsoft authors of articles need to make updates through the private repository so the updates can be staged and validated by the current validation rules. After you review staging and fix all validation issues, you can add the sign-off comment to let the PR reviewers know the updates are ready to be merged.It's easy to access the private repo version of your articles in GitHub. Just add -pr to the URL, as follows: 
 Public repo URL: https://github.com/MicrosoftDocs/azure-docs 
 Private repo URL: https://github.com/MicrosoftDocs/azure-docs-pr 
 We have closed this pull request. Please resubmit the updates through the private repo. For more information, [see the contributor guide].(https://docs.microsoft.com/en-us/contribute/)

**Review by EdPrice-MSFT — APPROVED** [review]
Great update

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger13** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @fbinotto, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
We'll move this commit to the private repo; metadata needs to be changed there. We'll post when the commit has been moved and the new PR is ready to merge in the private repo. Thanks.

**Comment by ktoliver** [comment]
We'll close this PR because the update is in a new PR in the private repo (pending response to PR review).

**Pull request closed without merging**
