### PR TITLE
added scenario 2 for deep learning

### PR DESCRIPTION
**Pull request by fboylu**

### CODE REVIEW

**Comment by PRMerger9** [comment]
@fboylu : Thanks for your contribution! The author(s) have been notified to review your proposed change. @njray

**Comment by jborsecnik** [comment]
@njray, I can't assign this to you for review (and neither could the system). It could be that your Microsoft and GitHub accounts are not linked. If not, see  [Link your GitHub and Microsoft accounts](https://review.docs.microsoft.com/en-us/help/contribute/contribute-get-started-setup-github?branch=master#link-your-github-and-microsoft-accounts).   Thanks.

**Comment by MikeWasson** [comment]
I'll review this PR - thanks!

**Comment by PRMerger7** [comment]
@MikeWasson : Thanks for your contribution! The author(s) have been notified to review your proposed change. @njray

**Comment by MikeWasson** [comment]
#sign-off

**Comment by PRMerger7** [comment]
@MikeWasson : Thanks for your contribution! The author(s) have been notified to review your proposed change. @njray

**Comment by PRMerger7** [comment]
@MikeWasson: I'm sorry - only the author of this article, @njray, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
