### PR TITLE
External configuration for limits/policies.Additional considerations

### PR DESCRIPTION
**Pull request by henrikwh**
Use of external configuration store should be applied. Additional considerations added.

### CODE REVIEW

**Comment by henrikwh** [comment]
#assign-reviewer: paolosalvatori

Needs one approving review. I guess you can approve Paolo?

**Review by paolosalvatori — APPROVED** [review]

**Comment by henrikwh** [comment]
#sign-off

**Comment by henrikwh** [comment]
@martinekuan can you review and signoff if ok?

**Comment by Court72** [comment]
@martinekuan 

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by martinekuan** [comment]
#sign-off

**Review by Jak-MS — APPROVED** [review]

**Pull request merged**
