### PR TITLE
Add Azure Red Hat OpenShift content into decision tree

### PR DESCRIPTION
**Pull request by pichuang**
- Fixed incorrect link for Spring Apps
- Add Azure Red Hat OpenShift content into Azure compute decision tree

### CODE REVIEW

**Comment by Jak-MS** [comment]
@EdPrice-MSFT 

Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by EdPrice-MSFT — APPROVED** [review]
Solid updates!

**Comment by EdPrice-MSFT** [comment]
@ckittel @josevarela 

Can we get an engineering review on these updates?

**Comment by ckittel** [comment]
I've requested that the ARO content dev from @rayoef's team, @johnmarco review this.  He manages the ARO content set and this is inline with his CSA.  Thank you @johnmarco.

**Review by rahulm23 — APPROVED** [review]

**Review by johnmarco — APPROVED** [review]

**Review by ckittel — APPROVED** [review]
Thanks @rahulm23 and @johnmarco!

**Comment by ckittel** [comment]
#sign-off

**Pull request merged**
