### PR TITLE
Routing ADDS Traffic via NVAs

### PR DESCRIPTION
**Pull request by nthewara**
Documentation states that we shouldnt pass ADDS Traffic via NVAs but there's no rational provided as to why this is not recommended ? In my view this is a support scenarios given we enable correct rules within the NVA. Most enterprise customers are using NVAs as an inspection point for traffic leaving Azure DCs and the fact this article specified we shouldnt use NVAs is conflicting with security practices.

### CODE REVIEW

**Comment by PRMerger7** [comment]
@nthewara : Thanks for your contribution! The author, @telmosampaio, has been notified to review your proposed change.

**Comment by jborsecnik** [comment]
@MikeWasson, I'm unable to assign to the author. I see you've made changes to this article. Can you review the changes here? Thanks.

**Comment by nthewara** [comment]
@jborsecnik  @MikeWasson  - Any update on this ?

**Comment by nthewara** [comment]
@jborsecnik @MikeWasson - Any update on this ?

**Comment by jborsecnik** [comment]
@MikeWasson, can you review this? If we should assign to someone else, let us know. Thanks.

**Comment by MikeWasson** [comment]
@nthewara @jborsecnik  I'll follow up - thanks!

**Comment by nthewara** [comment]
@mikewasson @jborsecnik any update on this ?

**Comment by doodlemania2** [comment]
Fixing merge conflict.

**Comment by MikeWasson** [comment]
@doodlemania2 Your merge commit overwrote the changes - please revert the commit. thx!

**Comment by MikeWasson** [comment]
Sorry for the merge/revert loop here. Rather than un-hork this branch I cherry-picked it into a new PR. Change should go live within a day.

**Pull request closed without merging**
