### PR TITLE
Additional detail about health checks when using message brokers

### PR DESCRIPTION
**Pull request by udidahan**

### CODE REVIEW

**Comment by Court72** [comment]
@msimecek 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by EdPrice-MSFT — APPROVED** [review]
Looks good

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Review by msimecek — APPROVED** [review]

**Comment by msimecek** [comment]
#sign-off

**Pull request merged**
