### PR TITLE
Update compute.md

### PR DESCRIPTION
**Pull request by BrianQu**
1. Add 'Amazon' and 'AWS' to service names.
2. Remove 'Logic Apps' from AWS Lambda functionality overlapping, since Azure Logic Apps is similar to AWS Step Functions (https://aws.amazon.com/step-functions/getting-started/) instead of AWS Lambda.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@BrianQu : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
Microsoft authors of articles need to make updates through the private repository so the updates can be staged and validated by the current validation rules. After you review staging and fix all validation issues, you can add the sign-off comment to let the PR reviewers know the updates are ready to be merged.It's easy to access the private repo version of your articles in GitHub. Just add -pr to the URL, as follows: 
 Public repo URL: https://github.com/MicrosoftDocs/azure-docs 
 Private repo URL: https://github.com/MicrosoftDocs/azure-docs-pr 
 We have closed this pull request. Please resubmit the updates through the private repo. For more information, [see the contributor guide].(https://docs.microsoft.com/en-us/contribute/)

**Review by EdPrice-MSFT — APPROVED** [review]
Good updates

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger14** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @BrianQu, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Review by EdPrice-MSFT — DISMISSED** [review]
The changes are good.

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger17** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @BrianQu, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
Hi @EdPrice-MSFT - The article author was updated 8/9 to a different value. Which would you like to use to resolve the merge conflict?

image

Thanks.

**Comment by ktoliver** [comment]
> Hi @EdPrice-MSFT - The article author was updated 8/9 to a different value. Which would you like to use to resolve the merge conflict?
> 
> image
> 
> Thanks.

We'll resolve in favor of the most recent update.

**Comment by PRMerger12** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by ktoliver — APPROVED** [review]

**Pull request merged**
