### PR TITLE
Update data-store-decision-tree.md

### PR DESCRIPTION
**Pull request by EdPrice-MSFT**
Updating to include ANF and specialized storage.

### CODE REVIEW

**Comment by PRMerger7** [comment]
@EdPrice-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @EdPrice-MSFT - This pull request was opened in the public repo. Would you like to close it and make the update in the private repo instead? Or we can merge it here as a one-off.

**Comment by EdPrice-MSFT** [comment]
We're checking to get our SAP HANA statement verified.

**Comment by EdPrice-MSFT** [comment]
> Hi @EdPrice-MSFT - This pull request was opened in the public repo. Would you like to close it and make the update in the private repo instead? Or we can merge it here as a one-off.

I'll move it over. Thanks!

**Pull request closed without merging**
