### PR TITLE
recreated PR : Updated graphics for the solution idea "DevOps in a hybrid environment" 

### PR DESCRIPTION
**Pull request by t2kx**
graphics were not showing correctly in Docs Darkmode theme , so updated graphics with light background so it can reflect correctly every (in any mode), and removed accidentally changed settings.json from PR

### CODE REVIEW

**Comment by PRMerger13** [comment]
@t2kx : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by t2kx** [comment]
replaces PR #2456

**Comment by doodlemania2** [comment]
#sign-off

**Comment by ktoliver** [comment]
@doodlemania2 I'm not able to merge the PR because of image file merge conflicts, presumably because this PR was just merged: https://github.com/MicrosoftDocs/architecture-center/pull/2432. From [what I read online](https://stackoverflow.com/questions/278081/resolving-a-git-conflict-with-binary-files), resolving a merge conflict in binary files requires working on the command line. I can move this commit to the private repo and then hand off the PR to you or @t2kx (and then close this PR), or I can close this PR and ask @t2kx to submit a new PR in the private repo. Which do you prefer?

**Comment by doodlemania2** [comment]
@t2kx - can you submit a new one to the private repo? Thanks @ktoliver

**Pull request closed without merging**
