### PR TITLE
Update design-segmentation.md

### PR DESCRIPTION
**Pull request by TristankMS**
Fix up spelling grammar and clarity

### CODE REVIEW

**Comment by PRMerger16** [comment]
@TristankMS : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@PageWriter-MSFT Could you review the proposed changes to your article? Thanks.

**Review by looody-438 — APPROVED** [review]

**Comment by ktoliver** [comment]
@doodlemania2 Could you review the proposed edits to the article? Thanks!

**Review by doodlemania2 — DISMISSED** [review]
#signoff

**Comment by PRMerger18** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@TristankMS @doodlemania2 - The meaning of "Isolating sensitive workloads from compromise of other assets" is unclear. Which would be accurate:

A) Isolating sensitive workloads from compromising other assets
B) Isolating sensitive workloads from being compromised by other assets

Thanks.

**Comment by TristankMS** [comment]
The proposed change is to "Isolating sensitive workloads from compromise _by_ other assets." If a sensitive workload is compromised, it's less important that it compromises other assets, it's the sensitive workload which is important.

**Review by ktoliver — APPROVED** [review]

**Comment by ktoliver** [comment]
@TristankMS Thanks--I made that edit and will merge the pull request now.

**Pull request merged**
