### PR TITLE
Update services.md

### PR DESCRIPTION
**Pull request by splitfinity**
Updates made to ## Internet of things (IoT)

### CODE REVIEW

**Comment by PRMerger19** [comment]
@splitfinity : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@EdPrice-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@EdPrice-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by EdPrice-MSFT — APPROVED** [review]
Great updates!

**Comment by PRMerger14** [comment]
@EdPrice-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger14** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @BrianQu, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger15** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by ktoliver — APPROVED** [review]

**Pull request merged**
