### PR TITLE
updated security capabilities that are supported

### PR DESCRIPTION
**Pull request by weslbo**
Connecting to a SQL Server instance that's running on an Azure virtual machine (VM) is not supported using an Azure Active Directory account. 

You can also connect to an Azure Database for PostgreSQL or MySQL using Azure AD (https://docs.microsoft.com/en-us/azure/postgresql/howto-configure-sign-in-aad-authentication and https://docs.microsoft.com/en-us/azure/mysql/concepts-azure-ad-authentication)

### CODE REVIEW

**Comment by PRMerger8** [comment]
@wedebols : Thanks for your contribution! The author(s) have been notified to review your proposed change. @zoinerTejada

**Comment by ktoliver** [comment]
Hi @doodlemania2 Could you take a look at this pull request? The listed author doesn't turn up in GitHub. Thanks.

**Comment by doodlemania2** [comment]
This looks accurate - likely a typo. #sign-off

**Comment by PRMerger16** [comment]
@doodlemania2: I'm sorry - only the author of this article, @zoinerTejada, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
