### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by splitfinity**
A few grammatical changes for consideration.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@splitfinity : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@EdPrice-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by EdPrice-MSFT — APPROVED** [review]
We'll take some of these edits. Thanks for your help!

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Pull request merged**
