### PR TITLE
Cross-linking to auto-scaling

### PR DESCRIPTION
**Pull request by udidahan**

### CODE REVIEW

**Comment by Court72** [comment]
@EdPrice-MSFT 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by ckittel — APPROVED** [review]

**Review by EdPrice-MSFT — APPROVED** [review]
Great update!

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Review by EdPrice-MSFT — APPROVED** [review]
Great update. Thanks!

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Pull request merged**
