### PR TITLE
Dark mode compatibility

### PR DESCRIPTION
**Pull request by ivcafe413**

### CODE REVIEW

**Comment by PRMerger14** [comment]
@ivcafe413 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@ivcafe413 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by doodlemania2** [comment]
#sign-off

**Comment by PRMerger7** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@doodlemania2 The "Download an SVG" link doesn't actually download a file. For me in GitHub Preview, the link opens the image in GitHub, and there's no download link (perhaps because of the file type): https://github.com/MicrosoftDocs/architecture-center/blob/19145000c009118e0493db85bff58a664f8fe62f/docs/example-scenario/multi-saas/media/multitenant-saas.svg

Do you want me to change the wording to "Get . . ." or "See . . ." or shall I merge it as-is? Thanks!

**Comment by doodlemania2** [comment]
@ktoliver  - Let's go as is please!

**Review by ktoliver — APPROVED** [review]

**Pull request merged**
