### PR TITLE
Extend Alternatives with Azure Cognitive Search

### PR DESCRIPTION
**Pull request by grecoe**
When using public Azure cloud, Azure Cognitive Search is a viable alternative.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@grecoe : Thanks for your contribution! The author, @njray, has been notified to review your proposed change.

**Comment by chbain** [comment]
@grecoe Although 'njray' is listed as the author in metadata, this person is not registered in GItHub or the GAL. You are the current assignee, so you will have to review and `#sign-off` this PR unless it should be reassigned.

**Comment by grecoe** [comment]
@chbain, thanks. I'm good with the change (as I created it of course). I didn't originally post it, so I'm not sure what the next step is, if you could just ping me and let me know if I just need to merge it or something else that would be great.

**Comment by MikeWasson** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@MikeWasson: I'm sorry - only the author of this article, @njray, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by chbain** [comment]
@grecoe Almost there. Please remove the `/en-us` link-locale from the URLs in lines 155 and 156. Normally I'd make this minor edit, but I can't make any changes in the arch-center repo.  Once you remove the two link locale instances, I can merge the commits. Thanks!

**Comment by grecoe** [comment]
@chbain interestingly enough, I can't edit the file from the pull request either? When I view the changed file and try to edit "You must be on a branch to make or propose changes to this file.". Also don't see a branch with my name on it. There are only a couple of lines added, I could, I suppose, just create another one?

**Comment by chbain** [comment]
@grecoe It appears there's an ongoing, intermittent bug that is preventing certain repos from being edited. Stand by...

**Comment by jborsecnik** [comment]
I'm unable to pencil edit now/still also.

**Comment by chbain** [comment]
@jborsecnik I plan to file a bug shortly.

**Comment by chbain** [comment]
Bug filed 6/24. Waiting on fix.

**Comment by Jak-MS** [comment]
@grecoe - it looks like the original working branch has been removed or something. can you re-push these changes to newly created working branch and then open a new PR? thanks.

**Comment by grecoe** [comment]
Just created a new PR with the changes. Let me know if there is anything else I need to do.

**Comment by Jak-MS** [comment]
thanks @grecoe - here's the new PR https://github.com/MicrosoftDocs/architecture-center/pull/1624 (for reviewer reference)

**Comment by ktoliver** [comment]
Closing this PR because it was replaced with https://github.com/MicrosoftDocs/architecture-center/pull/1624 (which has been merged).

**Pull request closed without merging**
