### PR TITLE
Broken image link fixed.

### PR DESCRIPTION
**Pull request by v-rajagt**

### CODE REVIEW

**Comment by ktoliver** [comment]
Hi @v-rajagt - This pull request was opened in the public repo. Microsoft vendors usually should open pull requests in the private repository for advanced quality validations and staging. To edit an article in the private repo from within the documentation, after you select **Edit** on an article page,  add “-pr” to the URL. We’ll leave this PR for review in the public repo, but would you make future article updates in the private repo?  Thanks!

**Comment by v-rajagt** [comment]
Hi @ktoliver Thanks for the information, I will take care of this in future. For should I need to close this PR and make changes in private REPO? Please advise. Thanks :)

**Comment by ktoliver** [comment]
Thanks @v-rajagt. I think we can leave the PR here, unless the content owner @adamboeglin responds differently. Thanks.

**Comment by v-rajagt** [comment]
Closing this PR as changes done in private repo.

**Comment by ktoliver** [comment]
> Closing this PR as changes done in private repo.

@v-rajagt Super! Thank you.

**Pull request closed without merging**
