### PR TITLE
ivcafe413 - Fixing Dark mode compatibility on couple of architectures

### PR DESCRIPTION
**Pull request by ivcafe413**
I was an original contributor to a number of the DevOps architectures, and noticed that I had not accounted for Dark Mode on the site. I have fixed up the two that I saw

### CODE REVIEW

**Comment by PRMerger12** [comment]
@ivcafe413 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @doodlemania2 - Could you review the PR? The .drawio file type isn't allowed in the repo, although I see 3 files with that extension in the repo now.

**Comment by doodlemania2** [comment]
#sign-off please add draw.io as an authorized file type!

**Comment by ktoliver** [comment]
Hi @doodlemania2 - I don't cover authorization of file types for the repo; the lead PR reviewer will reach out to the person who does (Cory Fowler).

But I can merge this after I check a couple things:

When I click to download the SVG, some of the images within the file are broken (in GitHub preview):

image

Is this OK? Will they build out during the build process?

Also, note that devops-in-a-hybrid-environment.png and devops-in-a-hybrid-environment.drawio are added, but no MD file is updated in the PR to reference these new images. OK?

Thanks.

**Comment by doodlemania2** [comment]
Hmm. - no that won't do. Let's close this for now and we'll reopen on the -pr side.

**Pull request closed without merging**
