### PR TITLE
Updating Event Hubs info

### PR DESCRIPTION
**Pull request by ShubhaVijayasarathy**

### CODE REVIEW

**Comment by PRMerger17** [comment]
@ShubhaVijayasarathy : Thanks for your contribution! The author(s) have been notified to review your proposed change. @zoinerTejada

**Comment by jborsecnik** [comment]
@MikeWasson, I can't assign this to the author. I see that you've modified this article several times. Are you able to review the requested changes? Thanks.

**Comment by MikeWasson** [comment]
LGTM

**Comment by PRMerger18** [comment]
@MikeWasson : Thanks for your contribution! The author(s) have been notified to review your proposed change. @zoinerTejada

**Pull request merged**
