### PR TITLE
Update aks-start-here.md

### PR DESCRIPTION
**Pull request by bahramr**
We were using the term "high availability" in the wrong context. Its hould be replaced with Disaster Recovery

### CODE REVIEW

**Comment by PRMerger8** [comment]
@bahramr : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@bahramr : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger3** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by ckittel — DISMISSED** [review]
Thanks!

**Comment by PRMerger3** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by ktoliver — APPROVED** [review]

**Comment by ktoliver** [comment]
Thanks, all. Merging now.

**Pull request merged**
