### PR TITLE
Typo "Azure Pipeline"→” Azure Pipelines”

### PR DESCRIPTION
**Pull request by hyoshioka0128**
https://docs.microsoft.com/en-us/azure/architecture/serverless/guide/serverless-app-cicd-best-practices
https://github.com/MicrosoftDocs/architecture-center/blob/main/docs/serverless/guide/serverless-app-cicd-best-practices-content.md
#PingMSFTDocs

### CODE REVIEW

**Comment by ShannonLeavitt** [comment]
Looks good; thanks @hyoshioka0128

**Review by EdPrice-MSFT — APPROVED** [review]
Great catch. Thanks!

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger14** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Review by EdPrice-MSFT — APPROVED** [review]
Great update

**Pull request merged**
