### PR TITLE
Update banking-system-cloud-transformation.md

### PR DESCRIPTION
**Pull request by bricewmiller**
Added "cse" to metadata for FCP PowerBI reporting

### CODE REVIEW

**Comment by PRMerger20** [comment]
@bricewmiller : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by doodlemania2** [comment]
#sign-off

**Comment by ktoliver** [comment]
Hi @bricewmiller - PMs should work in the private repo. Would you create future PRs in the private repo? Small updates like the one in this PR likely will auto-merge in the private repo, which is preferable to manual PR review on the public side. Thanks!

**Comment by bricewmiller** [comment]
@ktoliver, Thank you for the tip! I will figure out how to edit in the private repo to not create so many manual PRs for these small items.

**Pull request merged**
