### PR TITLE
Add link to discussion on implementing outbox

### PR DESCRIPTION
**Pull request by kbaley**

### CODE REVIEW

**Comment by Court72** [comment]
@cdennig 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by kbaley** [comment]
Hi @cdennig. Let me know if you need anything further from me for this.

**Comment by EdPrice-MSFT** [comment]
This seems to be a how-to on Particular's solution.

**Comment by kbaley** [comment]
@EdPrice-MSFT It's actually a discussion on the concepts involved in implementing your own outbox in whatever technology you like, including Cosmos DB and Azure Service Bus. It's similar to the link above it which shows an implementation of the domain events pattern.

Would it be better if the link text said "A sample implementation of the outbox"?

Would it be better to have the link text say "Sample implementation of an outbox"?

**Comment by kbaley** [comment]
Hey folks. Is it possible to have another look at this based on my comments above?

**Comment by kbaley** [comment]
@Court72 @cdennig I understand this is closed but was wondering if it could be reconsidered based on my previous comments

**Pull request closed without merging**
