### PR TITLE
Expand guidance on checkpointing long-running transactions

### PR DESCRIPTION
**Pull request by udidahan**
This PR carries over the guidance from the [autoscaling page](https://learn.microsoft.com/en-us/azure/architecture/best-practices/auto-scaling#application-design-considerations). While it might be even better to create a new design pattern for checkpointing, move the content there, and link to it from both places, I figured that would be more disruptive and we should possibly wait until there is a 3rd place that would require this info.

Let me know what you think.

### CODE REVIEW

**Comment by Court72** [comment]
@EdPrice-MSFT 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Court72** [comment]
@EdPrice-MSFT  - Could you review this proposed update to your article and enter `#sign-off` in a comment if it's ready for merge?

Thanks!

**Review by EdPrice-MSFT — APPROVED** [review]
Looks good!

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Pull request merged**
