### PR TITLE
Replace Data Catalog with Azure Purview

### PR DESCRIPTION
**Pull request by svchandramohan**
At line 132 the comparison is between AWS Glue and Data Catalog. AWS Glue IMO is a ETL tool and Data Catalog is a governance tool. Not sure it its a fair comparison. Also, Data Catalog should be replaced with Azure Purview

### CODE REVIEW

**Comment by PRMerger14** [comment]
@EdPrice-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by EdPrice-MSFT — DISMISSED** [review]
Great update

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger16** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @BrianQu, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger12** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by ktoliver — APPROVED** [review]

**Pull request merged**
