### PR TITLE
Adding comment on Serverless

### PR DESCRIPTION
**Pull request by WillEastbury**

### CODE REVIEW

**Comment by PRMerger16** [comment]
@WillEastbury : Thanks for your contribution! The author, @MikeWasson, has been notified to review your proposed change.

**Comment by MikeWasson** [comment]
Cost is a consideration but it doesn't directly affect SLA. From the current SLAs, Functions has same SLA as App Service and slightly less than zonal VMs

**Comment by Jak-MS** [comment]
@MikeWasson - are you still waiting for changes to this PR? Can you  provide specific guidance for this PR. 

- `#sign-off` if it's ready to merge
- `#hold-off` if it requires changes before it's ready for sign off
- `#please-close` - if these changes aren't going to be merged

Thanks!

**Comment by WillEastbury** [comment]
The single region SLA is the same yes, but functions doesn't double the cost to place the service in 2 regions. So the point is that you can get a higher sla for a similar price to single region compute.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by WillEastbury** [comment]
Mike responded to me today, I'll update the pr over the next few days with his comments.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by WillEastbury** [comment]
Hey Mike,

This will probably go into the CDP cost design docs anyway, feel free to drop the PR.

Thanks,
Will

**Comment by MikeWasson** [comment]
Makes sense - thanks!

**Pull request closed without merging**
