### PR TITLE
Updated files as per issue #3786

### PR DESCRIPTION
**Pull request by ajafry**
Added improved images as per https://github.com/MicrosoftDocs/architecture-center/issues/3786

### CODE REVIEW

**Comment by Jak-MS** [comment]
@EdPrice-MSFT 
- Can you review this PR? or reassign if someone else should review it?
- Note that for _docs/example-scenario/teams/media/securing-bot-image-009.png_ the private information is obscured by blurring, which is not permitted. It should be 'erased' (mask with background color) or fictionalized.

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by ajafry** [comment]
> 
@Jak-MS shall I upload a new image file with that issue fixed?

**Comment by EdPrice-MSFT** [comment]
@ajafry - Yes, please update 009.

Thanks!

**Comment by EdPrice-MSFT** [comment]
@ajafry - Do you have an ETA on updating the image?

Thanks!

**Review by EdPrice-MSFT — APPROVED** [review]
Looks good!

**Comment by EdPrice-MSFT** [comment]
#Sign-off

**Comment by ckittel** [comment]
@ajafry our reviewer, @ShannonLeavitt indicated that the quality of the images still isn't good. It's good that we removed the subscription information, but the suggestion was to get them added to a lightbox.  Is that something you can do in a new PR?  If so, I can direct you to our `-pr` repo so that you can get a good preview of the change.  Reach out to me on Teams to discuss.

**Pull request merged**
