### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by lukemurraynz**
Updated wording and sentence structure.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@lukemurraynz : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@EdPrice-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by EdPrice-MSFT — APPROVED** [review]
Good updates. Thanks!

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Pull request merged**
