### PR TITLE
Mentioning encryption as another consideration for message encoding

### PR DESCRIPTION
**Pull request by udidahan**

### CODE REVIEW

**Comment by Court72** [comment]
@PageWriter-MSFT 

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by Court72** [comment]
@PageWriter-MSFT  - Could you review this proposed update to your article and enter `#sign-off` in a comment if it's ready for merge?
Thanks!

**Comment by EdPrice-MSFT** [comment]
Editing looks good. 

@ckittel - Should we mention any other encryption resource?

Thanks!

**Comment by udidahan** [comment]
@EdPrice-MSFT I found something and linked to it. What do you think?

**Review by ckittel — APPROVED** [review]
LGTM!

**Comment by udidahan** [comment]
Thanks!

**Pull request merged**
