### PR TITLE
Update services.md

### PR DESCRIPTION
**Pull request by cjnova**
Adding Azure Dedicated Host vs sole-tenant-nodes to Compute section. Minor fixes (removed ending / in URLs)

### CODE REVIEW

**Comment by PRMerger18** [comment]
@cjnova : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@EdPrice-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by EdPrice-MSFT — DISMISSED** [review]
Changes are great!

**Comment by PRMerger13** [comment]
@EdPrice-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change. @fbinotto

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger15** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @fbinotto, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger17** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change. @fbinotto

**Review by ktoliver — APPROVED** [review]

**Pull request merged**
