### PR TITLE
fix: MD004/ul-style

### PR DESCRIPTION
**Pull request by nschonni**
Consistent unordered list style in document

### CODE REVIEW

**Comment by PRMerger9** [comment]
@nschonni : Thanks for your contribution! The author, @tracsman, has been notified to review your proposed change.

**Comment by ktoliver** [comment]
@tracsman Could you review the proposed changes?

From the Microsoft Docs contributor guide: "To format an unordered/bulleted list, you can use either asterisks or dashes." It doesn't specify using the same syntax within a file.

**Comment by doodlemania2** [comment]
Thank you so much for the contribution here. We're going to continue to improve the doc and close this one out for now. Please keep the great feedback coming!

**Comment by nschonni** [comment]
@doodlemania2 your canned response doesn't really make sense here, but i've deleted the branch anyway

**Comment by doodlemania2** [comment]
Sorry, didn't mean for it to be canned, I actually did type it :) We've got an alignment process starting up to make sure all of our formatting and such is consistent across the board. Appreciate the PR!

**Comment by nschonni** [comment]
There is #1522 for the markdownlint config. This was the only instance of inconsistent (within a page) list style

**Pull request closed without merging**
