### PR TITLE
Fix broken link & update old MSDN links to Docs.

### PR DESCRIPTION
**Pull request by kmgallahan**

### CODE REVIEW

**Comment by PRMerger13** [comment]
@kmgallahan : Thanks for your contribution! The author, @dragon119, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@Jak-MS : Thanks for your contribution! The author, @dragon119, has been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@Jak-MS : Thanks for your contribution! The author, @dragon119, has been notified to review your proposed change.

**Comment by jborsecnik** [comment]
confirmed correction

**Pull request merged**
