### PR TITLE
Removed duplicate sections

### PR DESCRIPTION
**Pull request by 0x1D-1983**
The paragraphs with the title "Understand the basic features" and "Consider limits and cost" appeared twice on the page with the exact same content. Kept the first appearances that fit better in the section order.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@0x1D-1983 : Thanks for your contribution! The author(s) have been notified to review your proposed change. @MikeWasson

**Comment by Jak-MS** [comment]
#assign: @MikeWasson

**Comment by PRMerger20** [comment]
MikeWasson is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by doodlemania2** [comment]
#signoff

**Pull request merged**
