### PR TITLE
Update application-logs.md

### PR DESCRIPTION
**Pull request by carmbell**
Extra ) in scala code and additional information on the jars

### CODE REVIEW

**Comment by PRMerger18** [comment]
@carmbell : Thanks for your contribution! The author(s) have been notified to review your proposed change. @PeterTaylor9999

**Comment by doodlemania2** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@doodlemania2: I'm sorry - only the author of this article, @PeterTaylor9999, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Review by doodlemania2 — APPROVED** [review]
#lgtm

**Pull request merged**
