### PR TITLE
613141- Article clean-up for thhickle: Azure AD join for Azure Virtual Desktop

### PR DESCRIPTION
**Pull request by vatmicro**
This pull request is for an article refresh according to [User story #613141]([url](https://dev.azure.com/ceapex/Contributor%20Success/_workitems/edit/613141/?triage=true))

### CODE REVIEW

**Comment by PRMerger3** [comment]
@vatmicro : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@vatmicro : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@vatmicro : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jborsecnik** [comment]
@TomHickling, 

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. Thanks.

**Review by EdPrice-MSFT — APPROVED** [review]
Updates look good. Thanks!

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger19** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @TomHickling, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by TomHickling** [comment]
#Sign-Off

**Pull request merged**
