### PR TITLE
add spring cloud link to toc

### PR DESCRIPTION
**Pull request by yucwan**

### CODE REVIEW

**Comment by yucwan** [comment]
#sign-off

**Comment by PRMerger13** [comment]
@yucwan: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
Hi @yucwan - This pull request was opened in the public repo. PMs should work in the private repo, per the Microsoft Docs contributor guide. Would you make this content update in the private repo instead? Thank you! We'll close this PR.

**Comment by yucwan** [comment]
moved to https://github.com/MicrosoftDocs/architecture-center-pr/pull/2516

**Pull request closed without merging**
