### PR TITLE
Add link to Azure Sphere docs

### PR DESCRIPTION
**Pull request by donntrenton**
In "Azure IoT reference architecture" (iot-content.md), in the first sentence of the "Devices" section, where "Azure Sphere" is mentioned, I added a link to the Azure Sphere home page (https://docs.microsoft.com/azure-sphere/product-overview/what-is-azure-sphere).

### CODE REVIEW

**Comment by jborsecnik** [comment]
@mcosner, are you the appropriate party to review these changes? (If you approve, I believe the URL needs to lose the ".md" to work.) Thanks.

**Comment by jborsecnik** [comment]
@mcosner, can you review this PR?

**Comment by mcosner** [comment]
From a content/IoT perspective this seems fine, but ultimately the azure architecture center team will have to approve the PR.

**Comment by jborsecnik** [comment]
> From a content/IoT perspective this seems fine, but ultimately the azure architecture center team will have to approve the PR.

@mcosner, Do you know who we can assign this to for review? Otherwise it will not advance.

**Review by EdPrice-MSFT — APPROVED** [review]
Looks great! Thanks!

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger15** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by donntrenton** [comment]
@jborsecnik is right, I need to remove the '.md' from the link URL; the link is broken.

**Comment by jborsecnik** [comment]
> @jborsecnik is right, I need to remove the '.md' from the link URL; the link is broken.

Hi. Sorry, I should have fixed this. I submitted a change just now to do so.

**Pull request merged**
