### PR TITLE
Update firewall-application-gateway-content.md

### PR DESCRIPTION
**Pull request by xsatishx**
Made changes to the following 

- [Application Gateway alone](#application-gateway-only), when only web applications are in the virtual network, and [network security groups (NSGs)][nsgs] provide sufficient output filtering. The functionalities provided by Azure Firewall can prevent many attack scenarios (such as data exfiltration, IDPS etc). Due to this reason Application Gateway Alone scenario isn't typically recommended and hence not documented and in the flow chart above.

Reason: The original sentence was too confusing as it uses words like this scenario and that functionality. I have simplified the sentence. Also might be worth adding a couple of more functionality that Az FW provides  since the wording says "rich functionality".

### CODE REVIEW

**Comment by ShannonLeavitt** [comment]
#label:"aq-pr-triaged"

**Comment by ShannonLeavitt** [comment]
@erjosito @EdPrice-MSFT - Could you review these proposed changes?

#label:"aq-pr-triaged"

**Review by erjosito — APPROVED** [review]

**Comment by erjosito** [comment]
LGTM!

**Review by EdPrice-MSFT — APPROVED** [review]
Made some minor style edits.

Looks great!

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger12** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Review by ckittel — APPROVED** [review]
LGTM

**Pull request merged**
