### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by bgener**
Added a note about gcp projects compared to the Azure subscription

### CODE REVIEW

**Comment by PRMerger12** [comment]
@bgener : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by EdPrice-MSFT — DISMISSED** [review]
Update looks good.

**Comment by PRMerger13** [comment]
@EdPrice-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger16** [comment]
@bgener : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@bgener : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by EdPrice-MSFT — APPROVED** [review]
Change looks good.

**Comment by PRMerger18** [comment]
@bgener : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by ktoliver — APPROVED** [review]

**Pull request merged**
