### PR TITLE
Adding the response status name "No Content"

### PR DESCRIPTION
**Pull request by aruanoguate**
This is a very simple change to increase the readability of the article.

I'm adding the response status name for 204 in the same way it's done for the rest of the document.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@aruanoguate : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by EdPrice-MSFT — APPROVED** [review]
That's helpful. Thanks!

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger16** [comment]
@EdPrice-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by ktoliver — APPROVED** [review]

**Review by ktoliver — APPROVED** [review]

**Pull request merged**
