### PR TITLE
Update government.md

### PR DESCRIPTION
**Pull request by lukemurraynz**
Rename Windows Virtual Desktop to: Azure Virtual Desktop

### CODE REVIEW

**Comment by PRMerger14** [comment]
@lukemurraynz : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by EdPrice-MSFT — APPROVED** [review]
Perfect! Thanks @lukemurraynz

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger13** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @dsk-2015, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
