### PR TITLE
Updated data flow, comoponents and next step for Digital Marketing

### PR DESCRIPTION
**Pull request by bhavinbdoshi**
Fixed Image size, added data flow, components and next step links for digital marketing using azure database for Postgresql

### CODE REVIEW

**Comment by bhavinbdoshi** [comment]
@EdPrice-MSFT

**Review by EdPrice-MSFT — DISMISSED** [review]
Looks great.

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger14** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Review by ktoliver — APPROVED** [review]

**Pull request merged**
