### PR TITLE
Update services.md

### PR DESCRIPTION
**Pull request by LazaUK**
Added Azure Synapse Analytics and Azure Databricks as alternatives to GCP Dataproc for the Spark-based analytics.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@LazaUK : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@EdPrice-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by EdPrice-MSFT — APPROVED** [review]
Great change

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger17** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @doodlemania2, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
