### PR TITLE
Update windows-virtual-desktop-content.md

### PR DESCRIPTION
**Pull request by TomHickling**
AAD Correction in limits table

### CODE REVIEW

**Comment by Jak-MS** [comment]
IMPORTANT: When this content is ready to merge, the reviewer must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by TomHickling** [comment]
#sign-off

**Comment by PRMerger10** [comment]
@TomHickling: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by Jak-MS** [comment]
@EdPrice-MSFT - can you take a look at this change? thanks.

**Comment by Jak-MS** [comment]
@EdPrice-MSFT - nevermind. I found previous approved changes to this content by @TomHickling ... merging this now.

**Review by Jak-MS — APPROVED** [review]

**Pull request merged**
