### PR TITLE
add cosmos security, availability considerations

### PR DESCRIPTION
**Pull request by lucashuet93**
- adds reference to cosmos ip restriction
- adds availability considerations for the cosmos account
- fixes markdown syntax

### CODE REVIEW

**Comment by ktoliver** [comment]
Hi @lucashuet93 I believe that the relative links in lines 82-94 (original) are correct and shouldn't be reversed. In the private repositories, automated validations are now requiring relative links for a successful pull request build. 

Also, as I noted in another pull request, Docs authors may equally use either supported syntax to create italic font (underscores vs. asterisks) or unordered lists (hyphens vs. asterisks). There isn't an organizational standard, and the diversity of usage in the content is essentially infinite.

**Comment by lucashuet93** [comment]
@ktoliver My apologies, I disabled my linter and re-pushed without all the formatting changes.

**Comment by ktoliver** [comment]
@lucashuet93 Thanks for very much for adjusting the PR for Markdown syntax revisions.

@tiburd @ckittel @EdPrice-MSFT Could someone on the team take a look at the proposed update to the article? Thanks.

**Review by EdPrice-MSFT — APPROVED** [review]
We ran an edit on the new paragraphs. Great updates.

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger16** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ktoliver** [comment]
@EdPrice-MSFT Your comment will do. :) I don't know what's expected for automation when the metadata for these files isn't set in the file. I'll look into it and open a bug if needed.

**Comment by ktoliver** [comment]
@EdPrice-MSFT Automation isn't working because the article metadata doesn't exist in the updated file; it resides in the YML file that hosts the MD file in the setup/layout for some of the AAC content. Engineering has created a bug to track efforts to resolve this: https://ceapex.visualstudio.com/Engineering/_workitems/edit/451875

Meanwhile, the PR review team sweeps for approved sign-offs regularly during the week. We will consider sign-off from you and members of the PNP FTE team authorized or we'll ask to confirm. We'll merge the PRs without further action on your side. Thanks for raising the issue.

**Pull request merged**
