### PR TITLE
Adds section about Pulumi as a declarative framework for IaC

### LINKED ISSUE #2289: Consider adding Pulumi to infrastructure deployment
[Pulumi](https://www.pulumi.com) is another tool for infrastructure deployment. It is Infrastructure as Software rather than IaC, with a hybrid imperative/declarative style, where you can deploy infrastructure using many programming languages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5490ef64-9b6d-59be-1e9b-a2b2d10388b2
* Version Independent ID: 4e37976c-47f3-1481-b312-e7be38f93e07
* Content: [Infrastructure Deployment - Azure Architecture Center](https://docs.microsoft.com/en-us/azure/architecture/framework/devops/iac)
* Content Source: [docs/framework/devops/iac.md](https://github.com/microsoftdocs/architecture-center/blob/master/docs/framework/devops/iac.md)
* Service: **architecture-center**
* Sub-service: **well-architected**
* GitHub Login: @Jose-Moreno
* Microsoft Alias: **pnp**

### PR DESCRIPTION
**Pull request by marcusturewicz**
Fixes #2289

### CODE REVIEW

**Comment by PRMerger19** [comment]
@marcusturewicz : Thanks for your contribution! The author(s) have been notified to review your proposed change. @jose-moreno

**Comment by doodlemania2** [comment]
#hold-off

**Comment by doodlemania2** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@doodlemania2: I'm sorry - only the author of this article, @jose-moreno, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ckittel** [comment]
I don't think that's the right Jose that PRMerger referenced @doodlemania2.  Can we check the owner of this?  Should it be @erjosito?

**Comment by doodlemania2** [comment]
Author is set to Jose M.

**Comment by ckittel** [comment]
image
guessing that should be @erjosito  (I'll feel really bad if it actually is the person that was tagged before, sorry if it was!)

**Pull request merged**
