### PR TITLE
Removed reference to doAzureParallel.

### PR DESCRIPTION
**Pull request by paterasMSFT**
doAzureParallel has been deprecated. Removing reference to it in the docs.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@paterasMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by AnalyticJeremy — APPROVED** [review]
looks good!  Thanks for the update!

**NOTE**: I do not have access to add labels so I cannot marked this as "approved".

**Comment by paterasMSFT** [comment]
@AnalyticJeremy thanks! Is there someone we need to comment to get the label/approval?

**Review by ktoliver — APPROVED** [review]

**Comment by ktoliver** [comment]
Hi - A team of PR reviewers look for and merge author-approved pull requests in this repository on a regular schedule.

**Comment by paterasMSFT** [comment]
Thanks, @ktoliver!

**Pull request merged**
