### PR TITLE
Update api-implementation.md

### PR DESCRIPTION
**Pull request by serpent5**
I noticed a few minor issues in the opening sections of this article.

### CODE REVIEW

**Comment by Jak-MS** [comment]
@MicrosoftDocs/patterns-and-practices-team-pr-reviewers 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by ckittel** [comment]
@serpent5 please review the CLA requirements above and indicate your intent.  We cannot proceed until signed.  If you do not agree to the terms, simply close the PR.

**Comment by serpent5** [comment]
@microsoft-github-policy-service agree

**Review by ckittel — APPROVED** [review]
Great updates, thank you.

**Comment by ckittel** [comment]
PnP #sign-off

#remove-label:"pnp-review-in-progress"
#remove-label:"do-not-merge"
#label:"ready-to-merge"

**Pull request merged**
