### PR TITLE
Update online-transaction-processing.md

### PR DESCRIPTION
**Pull request by HJToland3**
Updating based on current functionality for Azure database services for MySQL and PostgreSQL

### CODE REVIEW

**Comment by PRMerger15** [comment]
@HJToland3 : Thanks for your contribution! The author(s) have been notified to review your proposed change. @zoinerTejada

**Comment by Jak-MS** [comment]
@MikeWasson - can you review or re-assign? thanks.

**Comment by MikeWasson** [comment]
LGTM, thanks

#sign-off

**Comment by PRMerger18** [comment]
@MikeWasson: I'm sorry - only the author of this article, @zoinerTejada, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
