### PR TITLE
Removed link to etcd API in Azure Cosmos DB

### PR DESCRIPTION
**Pull request by Marusyk**
etcd API is no longer available
https://docs.microsoft.com/en-us/answers/questions/154061/about-etcd-support-in-azure-cosmos-db.html

Issue #3228

### CODE REVIEW

**Comment by PRMerger-2** [comment]
@Marusyk : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by PRMerger3** [comment]
@EdPrice-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by EdPrice-MSFT — APPROVED** [review]
Great. Thanks!

**Comment by EdPrice-MSFT** [comment]
#Sign-Off

**Comment by PRMerger18** [comment]
@EdPrice-MSFT: I'm sorry - only the author of this article, @dsk-2015, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
